### ISSUE TITLE
Modify processes pages so that they accept a process_id as parameter

### ISSUE THREAD

**Issue by josenavas** [jdereus/labman#101]
If the process id is present, load the pages with the process information pre-loaded, all the inputs disabled and, if there is any file to download, enabling the buttons to download those files (e.g. pooling file in `http://localhost:8080/process/poollibraries`

The pages that need to be modified:
- [x] `http://localhost:8080/process/gdna_extraction` @josenavas #106 
- [x] `http://localhost:8080/process/gdna_compression` @wasade #119 
- [x] `http://localhost:8080/process/normalize` #148
- [x] `http://localhost:8080/process/library_prep_16S` @josenavas #111
- [x] `http://localhost:8080/process/library_prep_shotgun` #148 
- [x] `http://localhost:8080/process/poollibraries` #148
- [x] `http://localhost:8080/process/poolpools` #148

**Comment by wasade** [comment]
I dont have edit permissions, but am starting on the `gdna_compression` page
