### ISSUE TITLE
Add grid showing sample ids on pooling

### ISSUE THREAD

**Issue by josenavas** [jdereus/labman#112]

**Comment by ElDeveloper** [comment]
Can someone provide a more in-depth explanation of this issue?

**Comment by josenavas** [comment]
@ElDeveloper, when the user has computed the values for pooling, this is what is shown to the user:

<img width="1215" alt="screen shot 2018-02-02 at 2 27 13 pm" src="https://user-images.githubusercontent.com/2501478/35757719-459c7492-0825-11e8-88cf-22a084d3815b.png">

The goal is to have another grid above or below that shows the sample plate layout (i.e. the layout when the user goes to 'Plate samples'). This way they can match the pooling values with the samples. Does that make sense?

**Comment by ElDeveloper** [comment]
Thanks @josenavas, this helps a lot!

**Comment by josenavas** [comment]
👍
