### ISSUE TITLE
Implement "undo" functionality when plating samples

### ISSUE THREAD

**Issue by josenavas** [jdereus/labman#120]

**Comment by ElDeveloper** [comment]
I think I can include this with the copy/paste PR. I have some progress 
on that front, but I still need to fix some bugs.

**Comment by josenavas** [comment]
Does SlickGrid support the undo functionality? If so that would be great - cause I was thinking on how I can keep a per-well history on the DB xD

**Comment by ElDeveloper** [comment]
Yes, I think it works, I have a WIP demo that supports copy/paste and 
undo/redo ... but there's some previous functionality that stopped 
working.

**Comment by josenavas** [comment]
Thanks @ElDeveloper ! Let me know if you have any questions/concerns with the previous functionality!

**Comment by ElDeveloper** [comment]
Actually, the undo/redo supported in SlickGrid only comprises the copy/paste functionality ... so this doesn't quite apply. Apologies for the confusion.

**Comment by josenavas** [comment]
Ok - no worries - thanks for looking into it!
