### ISSUE TITLE
Pooling Library crashes and doesn't work 

### ISSUE THREAD

**Issue by c1carpenter** [jdereus/labman#131]

**Comment by c1carpenter** [comment]
When I select "compute pooling values" the window flashes and then nothing happens, and I am not allowed to reselect the button. I believe it is supposed to give me a file (.csv), or a message at the minimum. 
![screen shot 2018-01-25 at 4 04 48 pm 2](https://user-images.githubusercontent.com/35116305/35418872-c18abd08-01e9-11e8-9c7d-183adf33700e.png)

**Comment by josenavas** [comment]
Hi @c1carpenter 

The system should be returning the pooling values and you should be able to visualize them in the screen. Is it possible that is just taking too long? In that case I think I just need to put some kind of visual feedback so you know the system is computing something.

Can you try again and just leave the page open for a minute or so to check if that's the case?

**Comment by josenavas** [comment]
Actually - I just noticed that you don't have an EpMotion selected. It should've not allowed you to click on 'Compute pooling values' unless you've selected one.

I saw that you're using Firefox - I'm wondering if it is a browser compatibility issue, I mainly test on Chrome so I will try on Firefox later to see if that's the case.

**Comment by c1carpenter** [comment]
I redid it with all the components selected, will report in a few minutes if something happens.

**Comment by c1carpenter** [comment]
Its weird, even if I fill it all in, and then select 'compute pooling values', nothing happens, however, I am allowed to add another plate if I desire to.

**Comment by josenavas** [comment]
Ok - I found the source of the problem - you can only proceed to library pooling if the plates have been quantified. I will limit the list of gDNA plates to show only those plates that have been quantified. I will also check why the interface was not reporting the error in the screen, since a big red banner should've been shown.

**Comment by c1carpenter** [comment]
Okay, so then the source of the problem is in the pico green section. I cannot proceed with quantifying my amplicon library plates because the plates are not pulling up, so when I proceed with 'pooling those amplicon plates' it isn't doing anything. got it. I guess then It should give me an error message correct? saying that the files i have selected do not have quantification values associated with them?

**Comment by josenavas** [comment]
Yes, once I work on it later today it should show plates only if they've been quantified. But in any case that should've shown an error message in the screen and it is troubling that it didn't.

**Comment by josenavas** [comment]
This should not occur anymore since you're only allowed to choose plates that have been quantified.
