### ISSUE TITLE
unclear what reformat button does under normalization 

### ISSUE THREAD

**Issue by c1carpenter** [jdereus/labman#137]

**Comment by josenavas** [comment]
@tanaes - I know what the goal of the checkbox is (reformat the plate from an interleaved patter to a  "plate" pattern) - but could you provide a user-friendly description of it so we can include it in the interface? I don't think my description above is good enough.

Thanks!

**Comment by tanaes** [comment]
Yup can do.

Also I think this actually breaks the compressed plate retrieval function,
which looks like it expects all four constituent plates to be present in
the top corner of the compressed plate.

**Comment by josenavas** [comment]
I don't think it breaks that functionality, because the reformat occurs on the normalized plate. The compress plate always has the interleaved format. does that make sense?

**Comment by tanaes** [comment]
Ah right, indeed it does.
