### ISSUE TITLE
Compress plate function is only pulling from my sample plates, not from my (gDNA) plates 

### ISSUE THREAD

**Issue by c1carpenter** [jdereus/labman#146]
![screen shot 2018-01-25 at 3 12 24 pm 2](https://user-images.githubusercontent.com/35116305/35417563-d1ee978e-01e2-11e8-8440-c07e44bc481f.png)

**Comment by adswafford** [comment]
Also, the gDNA plate compression happens with the epMotion and then goes on the Echo right? So shouldn't the robot option be the epMotion or are you trying to track that it goes into an Echo plate?

**Comment by josenavas** [comment]
@tanaes, can you confirm the point from @adswafford ? Now that he mentions it I do think it makes sense that the plate compression happens in the EpMotion, so I can easily change the equipment type being stored there.

**Comment by tanaes** [comment]
Yep it's just epMotion. Want me to make a PR with this change Jose?

**Comment by josenavas** [comment]
That would be great @tanaes Thanks!!!

**Comment by josenavas** [comment]
Fixed in #153
