### ISSUE TITLE
Add "Discard plate" functionality

### ISSUE THREAD

**Issue by josenavas** [jdereus/labman#150]

**Comment by tanaes** [comment]
What exactly is the scope of this functionality? Remove from database? Or update databases with a 'discarded' value to indicate the physical plate is gone?

**Comment by jdereus** [comment]
My understanding is to completely remove it.  In case someone in the wetlab totally messes up a plate and needs to throw it away.  Is there a reason to keep the plate in the db if it has been physically discarded?

Thanks,
Jeff D

**Comment by tanaes** [comment]
If for example a dna plate was used up in the process of enervating
libraries you’d want to keep it in the db. But I guess the ‘volume’
characteristic might help there. Still seems like having both the
indication of physical location or disposition would be useful
independently of being able to undo a mistaken plate entry...

**Comment by josenavas** [comment]
The goal of this issue is to just update the "discard" column on the DB but not delete it. Deletion is always dangerous and I prefer to refer that functionality until we understand clearly when something can be deleted. From the point of view of the user, discard should be equal to delete, in the sense that the plate is not visible in the interface.

**Comment by ElDeveloper** [comment]
If I understand correctly then this is a matter of changing the store in the DB and if a plate is marked as "discarded" then don't show it on screen. I think I can tackle this one.
