### ISSUE TITLE
plate compression not pulling gDNA plates 

### ISSUE THREAD

**Issue by c1carpenter** [jdereus/labman#166]
![screen shot 2018-01-29 at 12 25 14 pm 2](https://user-images.githubusercontent.com/35116305/35532582-8ee31b9e-04ef-11e8-8537-77c6d771f517.png)

**Comment by c1carpenter** [comment]
The machine it should be using i believe should be an epMotion as well.

**Comment by tanaes** [comment]
Fixed in #153
