### ISSUE TITLE
Blank/control values need more flexible typing

### ISSUE THREAD

**Issue by tanaes** [jdereus/labman#172]
Currently, there are three preset control types:

 - blank:	gDNA extraction blanks. Represents an empty extraction well.
 - vibrio.positive.control:	Bacterial isolate control (Vibrio fischeri ES114). Represents an extraction well loaded with Vibrio.
 - zymo.mock:	Bacterial community control (Zymo Mock D6306). Represents an extraction well loaded with Zymo Mock community.

Hard coding this is probably a mistake, as there are different kinds of blanks (e.g. empty swab, extraction reagents, empty well) and likely many pore positive controls. 

Furthermore, anything can be coded as a sample and entered as positive information. Storing these controls is mostly 1) as a convenience, and 2) to allow API-assured access to certain types of control for downstream processing. 

Finally, in the plating interface, the behavior of these blanks should be more expicit -- i.e. currently, empty wells are designated blanks upon storing, but not visually prior. A 'fill blanks' button or something might do.

**Comment by josenavas** [comment]
@tanaes Do you think that 'empty' would be a good name to use for those wells that we don't want to go through library prep?

**Comment by ElDeveloper** [comment]
One more question on this, should empty cells be initialized as being "blank", there's some dissonance between things that are empty and things that are "blanks". From what I can tell things that are empty get transformed into blanks but explicitly blank cells are also blanks.

**Comment by josenavas** [comment]
Yeah, I think if 'empty' is a good definition, we should initialize them as empty.

**Comment by tanaes** [comment]
I think we should check in with Greg on this one.

**Comment by josenavas** [comment]
I've just discuss this with Greg. 'empty' would be a good nomenclature - however they request for the default on the plate be 'blank' since that is the most common use case.

@tanaes the 'empty' approach in the plate compression already occurs automatically - so that's not a problem there, and Greg only sees the 'empty' approach useful during plating in case of a Rapid Response, since in general they do complete plates (including blanks).
