### ISSUE TITLE
Platemap UI duplicates entered values

### ISSUE THREAD

**Issue by ElDeveloper** [jdereus/labman#178]
If you type in a value in the spreadsheet UI, it duplicates the value in the cell to the right when you hit tab or enter. 

![33333](https://user-images.githubusercontent.com/375307/35647853-c12858fe-0688-11e8-8235-f987a78eabdf.gif)

**Comment by josenavas** [comment]
Thanks @ElDeveloper I think this is a result from the changes that you performed correcting the indices. Note that I didn't review that PR, but there is a likelihood that there are instances in which the indices where not corrected accordingly.
