### ISSUE TITLE
Plate samples: well highlighting is persistent after contents change

### ISSUE THREAD

**Issue by tanaes** [jdereus/labman#189]
I noticed that while plating samples, if I add a duplicate sample both wells are highlighted, but the original well remains highlighted until I select it again:

![feb-06-2018 09-32-44](https://user-images.githubusercontent.com/8292608/35876047-fb739ff4-0b25-11e8-80a8-f30b26c65d67.gif)

This is also true if entering an unrecognized sample:

![feb-06-2018 10-10-51](https://user-images.githubusercontent.com/8292608/35876086-1356c524-0b26-11e8-9559-80ce974a8739.gif)

**Comment by ElDeveloper** [comment]
I'll have a look at this.
