### ISSUE TITLE
"stress_test" command for tester.py suggests server side issues with scalability

### ISSUE THREAD

**Issue by wasade** [jdereus/labman#199]
Executing "stress_test" with a few hundred plates leads to an increasing time estimate on the progress bar. This suggests the load times increase as a function of the volume of data in the database which seems surprising. It is not clear what method or methods are driving the increasing load times but this should be an easy target to profile or just decorate with timing statements.

**Comment by wasade** [comment]
To refine, this is associated with the "Sample plating process". I haven't let the stress test run out further yet

**Comment by AmandaBirmingham** [comment]
I am subsuming this issue into #173.
