### ISSUE TITLE
Recomputing pooling values creates overlapping plots

### ISSUE THREAD

**Issue by ElDeveloper** [jdereus/labman#206]
It is mostly noticeable on the colorscale.

**Comment by AmandaBirmingham** [comment]
To reproduce: 
* Go to Pools > Pool library plates
* Choose "Shotgun library plates" in the Plate Type dropdown
* Click the "Add Plate" button
* Click the "Add" icon for plate 26
* Choose "Equal volume" in the Pooling Function dropdown
* Click "Compute pooling values"
* After graphics are displayed, return to Pooling Function dropdown and select "Minimum Volume"
* Click "Compute pooling values" 

This produces overlap in the graphics, as shown here:
![screen shot 2018-03-13 at 4 09 16 pm](https://user-images.githubusercontent.com/10677935/37374766-e48a1e7e-26d9-11e8-900b-cae3c7faabee.png)

**Comment by AmandaBirmingham** [comment]
Ok, I think I see what's driving this: 
https://github.com/jdereus/labman/blob/0b36cfb63e8222f078f2479c9651e225864fb9c1/labman/gui/static/js/labman.js#L298 
.... gets the pool results element, and then 
https://github.com/jdereus/labman/blob/0b36cfb63e8222f078f2479c9651e225864fb9c1/labman/gui/static/js/labman.js#L324-L325
... appends a heatmap and histogram to this element, but there is no step that cleans the contents of the pool results element out if createHeatmap has been called on the page before.  Hopefully pretty easy to fix.

@ElDeveloper or @tanaes please clarify the desired behavior: do we want the plots to show ONLY the visualization of the most recently computed pooling values?

**Comment by ElDeveloper** [comment]
@AmandaBirmingham, that does look like the problem 👍

Yes, I believe we only want to show the visualization of the most recently computed pooling values.

**Comment by tanaes** [comment]
Yep, this sort of an interactive check to make sure they're good to go
before storing to DB.
