### ISSUE TITLE
Project ID Prepending

### ISSUE THREAD

**Issue by Lindsaydg** [jdereus/labman#209]
From the image, you can see that for American gut, the sample comes up as red unless the “10317” study ID is present… which creates another issue because then the user cannot see what the barcode actually is, it just gets cut off. Also, this of course makes both copy and pasting as well as scanning in the barcodes less effective because I then need to go back and add the study ID to verify that the sample is ok. 

<img width="1222" alt="screen shot 2018-02-22 at 09 30 25" src="https://user-images.githubusercontent.com/36741726/36555185-1ab53d54-17b6-11e8-9a10-e3a517d32057.png">

**Comment by ElDeveloper** [comment]
@Lindsaydg would a button that adds the study identifier to all the samples do the trick? Or do you usually have samples from multiple studies that require a study identifier to be prepended?

One last question is this an AG-specific issue?
