### ISSUE TITLE
Cells with lots of text

### ISSUE THREAD

**Issue by Lindsaydg** [jdereus/labman#210]
If there is too much text in a cell, it just fits part of the name then adds “…”. This may vary from person to person, but I prefer to just make the cells wide enough so that I can see all the text without having to click on the individual cells. Is it possible to increase the cell width to allow for all/more characters to be seen?
And tiny side note, you can also see that the column headers (#1-12) are slightly cut off at the bottom. Can they be shifted up a bit?
<img width="96" alt="screen shot 2018-02-22 at 09 42 29" src="https://user-images.githubusercontent.com/36741726/36555317-74a5eae8-17b6-11e8-8f31-43d02c672b11.png">

**Comment by ElDeveloper** [comment]
@Lindsaydg These are all great suggestions and possible changes for sure. Would it make sense to increase the default width of these cells to at least twice the width? And in addition add the ability to resize the width of the columns at the user's will?

As for the headers, yes I can look into that.

**Comment by Lindsaydg** [comment]
I would say maybe a 25% increase in the default width since most sample IDs would probably fit and it is nice to see the whole plate without having to scroll. And yes, for the longer sample names being able to adjust the column width would be fantastic.

**Comment by ElDeveloper** [comment]
Excellent, thanks for the info :+1:
