### ISSUE TITLE
Pool library plates with Pooling function = Floor volume produces silent, fatal error

### ISSUE THREAD

**Issue by AmandaBirmingham** [jdereus/labman#213]
To reproduce:

* Go to Pools > Pool library plates
* Choose "Shotgun library plates" in the Plate Type dropdown
* Click the "Add Plate" button
* Click the "Add" icon for plate 26
* Choose "Floor volume" in the Pooling Function dropdown
* Click "Compute pooling values"

Outcome:
* No results are returned
* No error message is shown
* "Compute pooling values" and "Pool" buttons remain disabled indefinitely

Cause: 
Looking at the javascript console shows an internal server error in the call to the process/compute_pool URL:
![screen shot 2018-03-13 at 4 43 37 pm](https://user-images.githubusercontent.com/10677935/37375616-b58203a4-26dd-11e8-84f3-9fad8459b950.png)

Running the debugger on the back-end shows the server error is in ComputeLibraryPoolValueslHandler > BasePoolHandler > _compute_pools: 
https://github.com/jdereus/labman/blob/0b36cfb63e8222f078f2479c9651e225864fb9c1/labman/gui/handlers/process_handlers/pooling_process.py#L222

where function is PoolingProcess.compute_shotgun_pooling_values_floor .  The call to this function throws the error "The function compute_shotgun_pooling_values_floor() got an unexpected keyword argument 'floor_vol'".

**Comment by tanaes** [comment]
I'll fix this in my PR #203

**Comment by tanaes** [comment]
Fixed in #203
