### ISSUE TITLE
run_date column in process table is defined as date rather than timestamp

### ISSUE THREAD

**Issue by AmandaBirmingham** [jdereus/labman#215]
The process table stores info on all the different sorts of processes (sample plating, extraction, quantification, etc) that can be performed through Labman.  Since there can be multiple processes of the same type performed on the same plate or well, the process table stores *when* each process was performed to help disambiguate between them.  For this purpose, we need to store the full date+time (timestamp) of when the process was performed, not just the date, as multiple of the same sort of process might well be performed on the same date.

(This one is probably my fault: when I laid out the database schema, I specified this field as a date, not knowing that in Postgres, the "date" data type doesn't capture full datetime info https://www.postgresql.org/docs/9.1/static/datatype-datetime.html ).

**Comment by AmandaBirmingham** [comment]
I've got a fix ready for this which changes the process run_date's type to a timezone-aware timestamp but need input from the team (I'm looking at you @tanaes @ElDeveloper  :) ) on three issues:
1) The "external_id" for primer working plates is created automatically and incorporates the process date:

https://github.com/jdereus/labman/blob/1bfe656175a72fcf54662fa5a23c11fc324b4e42/labman/db/process.py#L385-L397

Do we want this to stay as it is (including only YYYY-MM-DD of creation timestamp) or do we want it to include the full timestamp, in case more than one plate is created that day?

2) Similarly, _generate_amplicon_sample_sheet and _generate_shotgun_sample_sheet both place the date of the SequencingProcess into the sample sheet header (using the exact same code :( ):

https://github.com/jdereus/labman/blob/1bfe656175a72fcf54662fa5a23c11fc324b4e42/labman/db/process.py#L2814-L2821
https://github.com/jdereus/labman/blob/1bfe656175a72fcf54662fa5a23c11fc324b4e42/labman/db/process.py#L2778-L2785

Do we want this to be changed to the timestamp of the SequencingProcess or keep it as just YYYY-MM-DD?

3) Finally, do we want to change the actual name of the database field/Process property to something other than "run_date"?  I'm ok with keeping it as is, but if y'all feel that the name is misleading for a field that is really a timestamp in postgres, we can change it.

**Comment by jdereus** [comment]
I do not use a date from the sample sheet.  The output directory is based on the name of the output directory generated by the sequencing machine.

Run date is not very accurate if I understand what you are discussing here.  Just because you generated a sample sheet on a specific day does not mean you are running on that day.  There is sometimes quite a lag.

Thanks,
Jeff D

**Comment by ElDeveloper** [comment]
Indeed, thanks for looking into this @AmandaBirmingham.

In general I agree with @tanes. However, I would say that if the changes are not too complicated to make including hours and minutes could be better, if only for any unforeseen edge-case situation that might arise in the future.

**Comment by AmandaBirmingham** [comment]
@jdereus You wrote "Run date is not very accurate if I understand what you are discussing here.  Just because you generated a sample sheet on a specific day does not mean you are running on that day."

Ah, I see your concern, but I think (hope?) this is just a collision of terminology!  The "run" being referred to in the "run_date" column of the qiita.Process table is not a *sequencing* run; rather, it indicated the date that the recorded Labman process was run (and exists for all types of Labman processes, including quantification, sample plating, etc).  I'm open to a better name that would reduce this source of confusion if anyone wants to pitch one ... maybe process_date?

**Comment by jdereus** [comment]
Thanks.  That helps my understanding.

However, please realize that I still do not use that date for anything that relates to bcl conversion after the run is complete off the sequencer.  So the sample sheets would then need separate dates in them to clearly separate when they were created.  If there is a need to fix/recreate a sample sheet, it does not make sense to me to keep the original date of sheet creation.  It will make it harder to determine which sample sheet is the most recent sheet.

Maybe you have information somewhere else that tracks that.

Thanks,
Jeff D

**Comment by AmandaBirmingham** [comment]
@jdereus Hmm, I fear both of us may be getting more confused :( 

The date that Labman writes into the sample sheet IS the date on which that sheet was created by Labman (because there is a Labman "process" for creating sample sheets, and the date that this process is run is the date that goes into the sample sheet that process creates as output). 

>So the sample sheets would then need separate dates in them to clearly separate when they were created
This already happens, since date in the sample sheet actually is the date on which the sheet was created.  (That date probably *isn't* the same as the date on which sequencing run for the samples in that sheet was actually done; Labman has no knowledge about when actual sequencing happens.)

> If there is a need to fix/recreate a sample sheet, it does not make sense to me to keep the original date of sheet creation.
If a sample sheet is re-generated through Labman, then it will have the date it was RE-generated in it; fortunately, there is actually no way for it to end up with the date of the "original" sample sheet :) 

Based on the above, I *think* that the date in the sample sheet already contains the info you want/need it to.  If I'm misunderstanding, though, please correct me!

**Comment by AmandaBirmingham** [comment]
Fixed via pull request #240
