### ISSUE TITLE
question on gDNA extraction

### ISSUE THREAD

**Issue by jdereus** [jdereus/labman#22]
what is the purpose of the extraction kit/volume pop up?  when adding a value to the extraction kit box, new extraction kit pop up presents itself.  the lot ID is the same as entered but the volume is different from the Extraction Volume (ml) on gdna_extraction page.

**Comment by josenavas** [comment]
The goal of that pop up is to actually create the extraction kit on the system. As discussed on the meeting, that volume is not needed so I'm going to remove the input. However, I will leave the pop up as that would work as confirmation to create the new Extraction Kit (and in general reagent) in the system.
