### ISSUE TITLE
Mutually exclusive login between labman and qiita

### ISSUE THREAD

**Issue by ElDeveloper** [jdereus/labman#223]
Seems like a user can't log to both websites under the same username at the same time. At least not without being logged out.

Steps to reproduce:

- Open a new browser window.
- Login to labman with your username.
- Login to qiita with the same username as in the previous step.
- Interact with the qiita UI.
- Go back to labman and interact with the UI, by now you will notice that most functionality is disabled and or will see errors as you have now been logged out.

**Comment by josenavas** [comment]
This can be solved by using the same cookie secret on both servers when launching them.

**Comment by antgonza** [comment]
Just tested this in maptest/qiita and is not happening. Also, after chatting with @ElDeveloper he remembers that this used to happen in his local install ... thus, closing.
