### ISSUE TITLE
Clicking "Prepare sequencing pool" button on "Pool list" page gives 404 error

### ISSUE THREAD

**Issue by AmandaBirmingham** [jdereus/labman#232]
Do this:

![screen shot 2018-05-02 at 11 07 40 am](https://user-images.githubusercontent.com/10677935/39788847-2fd2b674-52e1-11e8-89fc-0997143aae70.png)

... and click "Prepare sequencing pool", and you get this:

![screen shot 2018-05-02 at 11 07 48 am](https://user-images.githubusercontent.com/10677935/39788863-4483a330-52e1-11e8-98df-c1075813fdd2.png)

This isn't an issue with any particular pool or set of pools; it is because there is no handler defined for "/process/pool" :(

I'm guessing that this button-press should actually route to "/process/poolpools$', to be consumed by the gui/handlers/process_handlers/pooling_process.py PoolPoolProcessHandler , since that is where the "Prepare amplicon sequencing pool" menu item goes.  @tanaes @ElDeveloper do you concur?

**Comment by ElDeveloper** [comment]
@AmandaBirmingham, yes I think you are right!

**Comment by tanaes** [comment]
Yes I believe this is the case! I think early on Jose had only considered
the single pooling process type.

**Comment by josenavas** [comment]
It looks like when the links where changed to "/process/poolpools/" and "/process/poollibraries/", the logic behind that button wasn't updated. Should be a change on the JS.

**Comment by tanaes** [comment]
Fixed with #236
