### ISSUE TITLE
Divide by zero in _compute_amplicon_pool_values

### ISSUE THREAD

**Issue by AmandaBirmingham** [jdereus/labman#233]
In db/process.py _compute_amplicon_pool_values, this line

https://github.com/jdereus/labman/blob/0dd5afef6a980ff25d6b420618828a2bddae383c/labman/db/process.py#L1890

sometimes generates:

RuntimeWarning: divide by zero encountered in true_divide

Is having a zero sample concentration valid?  If so, perhaps we should handle that condition rather than letting it spit warnings ...

**Comment by tanaes** [comment]
Hmm, good point -- yes it's possible for these to be zero and we need to be
able to handle that.

**Comment by tanaes** [comment]
...is it that line or is it here?

https://github.com/jdereus/labman/blob/0dd5afef6a980ff25d6b420618828a2bddae383c/labman/db/process.py#L2022-L2028

In PR #203 we actually should have removed any use of `_compute_amplicon_pool_values` method.

**Comment by AmandaBirmingham** [comment]
No, the warning I was getting was definitely from the "return float(dna_amount) / sample_concs " line--but I saw it a while ago and just got around to logging it.  So maybe it is now gone :)

**Comment by tanaes** [comment]
In any case it should be a problem and it helped me catch that deprecated
method, so thanks! :)

**Comment by tanaes** [comment]
Fixed with #235
