### ISSUE TITLE
Include lane column/number in sample sheets for multilane sequencers

### ISSUE THREAD

**Issue by tanaes** [jdereus/labman#239]
Original issue name: Need per-lane pool assignment in 'Prepare sequencing run' interface

Currently, there is no mechanism to assign sequence pools to individual lanes (e.g. 8 lanes of HiSeq4000 or 2 lanes of HiSeq2500). 

I'd imagine that we'd want to have the interface load the number of lane slots appropriate to the sequencing instrument once that instrument is loaded, and then allow just a single pool to be added per lane.

**Comment by AmandaBirmingham** [comment]
It appears this issue is a bit different than originally thought.  The existing code in labman.db.process.SequencingProcess.create expects to take in "The pools being sequenced, in lane order", and it does store the lane numbers associated with each pool (as implied by that order) into the qiita.sequencing_process_lanes table.  I checked with Greg H. today, and he says that he is ok (at least for now) with the lane number for each pool being implied by the order in which it is added to the sequencing run.

Unfortunately, the existing code DOESN'T output the lane information into the sample sheets produced, which is a bug.  Greg indicates that for both 16s and shotgun sample sheets, for sequencers that have more than one lane, each row should start with a "Lane" column holding the (1-based) lane number.  For 16s (amplicon) sample sheets (only), there should be one row per lane and each row should have the prescribed string of Ns in the index column.

**Comment by AmandaBirmingham** [comment]
Did a bit of investigation here; the labman.db.process.SequencingProcess. _generate_shotgun_sample_sheet method IS lane-aware (via _format_sample_sheet_data).  However, _generate_amplicon_sample_sheet is NOT, and will need a bit of a rewrite to make it so.

**Comment by AmandaBirmingham** [comment]
@qiyunzhu please take a look at the details above watch this space in case I get any more info from Greg :)

**Comment by qiyunzhu** [comment]
@AmandaBirmingham Yes I am tracking this thread :) Thanks for all the information!

**Comment by qiyunzhu** [comment]
Hi @tanaes @AmandaBirmingham I created a pull request #268 to address this issue.

Currently, the "Lane" column has been successfully added to the amplicon sample sheet. This was achieved by modifying the `_generate_amplicon_sample_sheet` function.

However I felt that this function was originally flawed. It only generates one row of the whole sample sheet, rather than the entire sample list, as the counterpart `_generate_shotgun_sample_sheet` does.

Did I miss something? I would appreciate if either of you can confirm!

**Comment by AmandaBirmingham** [comment]
Yes, @qiyunzhu , your intuition is correct--a correct amplicon sample sheet requires that there be more than one row (one for each lane) in the case where the sequencer being used has multiple lanes.  And I agree that the `_generate_amplicon_sample_sheet` function was originally flawed in that it does not support such multiple rows; fixing that flaw is what this issue is about :)

**Comment by qiyunzhu** [comment]
Hi @AmandaBirmingham thanks for the feedback! Looks to me that `_generate_amplicon_sample_sheet` was but a mock. In addition to not supporting multiple row, it also does not read the actual sample information at all. I can try to re-engineer it based on `_generate_shotgun_sample_sheet`, which looks quite complicated. Please let me know if this is not the right direction. Thanks!

**Comment by tanaes** [comment]
Hey Qiyun,

Because for our amplicon pipeline the samples are demultiplexed downstream,
it's really important that each lane be represented by a separate line on
the sample sheet. Check with Greg  for how they like these to look. I don't
think it will necessarily need to access any sample data for these.

**Comment by AmandaBirmingham** [comment]
@qiyunzhu I do not believe it is accurate that `_generate_amplicon_sample_sheet` is a mock.  While I am no expert in sample sheets, I believe based on my discussion with Greg yesterday that the existing code produces the correct sample sheet output for a MiSeq sequencer (only).  For that single-lane sequencer, the sample sheet [Data] section should indeed include a single data line of the form below:
<img width="637" alt="screen shot 2018-07-25 at 3 12 18 pm" src="https://user-images.githubusercontent.com/10677935/43230484-4818b002-901d-11e8-81ef-603087b3aa8b.png">

Note that the contents of the column "Sample_ID" are not actual sample ids but rather a single name for all the stuff being run in that lane.  When there is only one lane being run, there is only one line total, and it only has two fields filled in.

Right now the name for the one produced row is coming from the name of the RUN, which won't be different for different lanes.  I assume it will be necessary to change it to something else when you expand this method to produce one row per lane, and we should check with Greg what that something else would be ... my best guess is the name of the pool being run on that lane.

**Comment by qiyunzhu** [comment]
Here is how it looks like :) @AmandaBirmingham @tanaes 
![screen shot 2018-07-25 at 4 32 32 pm](https://user-images.githubusercontent.com/4396343/43232947-fc117356-9062-11e8-8cfd-ce0b151ae276.png)

**Comment by AmandaBirmingham** [comment]
@qiyunzhu as far as I know, PoolCompositions themselves don't have names or descriptions.  However, when the Labman user creates a pool, they fill in a name--and where that actually gets assigned is as the  "external_id" of the *tube* for the pool.  See below:

https://github.com/jdereus/labman/blob/e9bbb29d162164292b87f6193c42a5f59199d8df/labman/db/process.py#L2188-L2191

So to get the human readable name for the PoolComposition you are working with, you will need to access `yourPoolCompositionObject.container.external_id`.  HTH :)

**Comment by qiyunzhu** [comment]
Hi @AmandaBirmingham thanks! The `container` trick worked! Now it looks like:
![screen shot 2018-07-25 at 5 07 04 pm](https://user-images.githubusercontent.com/4396343/43233835-d35d7bda-9067-11e8-922e-c31ae1b9c4f5.png)
Does it look good?

**Comment by qiyunzhu** [comment]
Hello @AmandaBirmingham thanks for the further comments! Yeh let's wait for confirmation on the lane column question then! Coding-wise it shouldn't be very hard to make a logic switch.

**Comment by AmandaBirmingham** [comment]
Summary of the current questions and info gathered on them?

1) Is it accurate that there MUST be a Lane field in sample sheets for the single-lane sequencers OTHER THAN MiSeq?  (e.g., MiniSeq, NextSeq, NovaSeq)
* No one has ventured an answer for this question.
* Greg says "I have never worked with the other single lane sequencers sample sheets."
* The illumina bcl2fastq2 Conversion v2.19 User Guide (https://support.illumina.com/content/dam/illumina-support/documents/documentation/software_documentation/bcl2fastq/bcl2fastq2_guide_15051736_v2.pdf ) lists MiSeq, MiniSeq, NextSeq, and NovaSeq among the instruments covered by the sample sheet conventions it describes.

Answer to 1:
 **Therefore**, until/unless someone provides a concrete reason not to, the Labman code will generate MiSeq-style sample sheets for all single-lane sequencers.  This means there will be NO "Lane" column in the sample sheets for ANY single-lane sequencer.

2) What pool descriptor should go into the Sample_ID column?
* This started out as a question specifically about multi-lane sequencer sample sheets but has changed as we gathered more info.
* The current value used by Labman (run name) is clearly inadequate, especially for multi-lane sequencers.
* The two kinds of values currently being considered are the (positive integer) "composition_id" of the pool and the (free text) "external_id" of the tube associated with the pool.
* Greg says "IGM uses the sample sheet to determine which pool to load on which lane, and I would prefer to not hand them a group of tubes with just numbers".
* Rob suggests putting composition_id in the Sample_ID column and external_id in the Sample_Name column.
    * Kristen Jepsen says of that suggestion: "If the Sample_ID and Sample_Name columns do not match, the FASTQ files are placed in an additional sub-directory named by the SampleId.  I think that will be a pain for you."
    * Greg says of that suggestion: "that will only work for amplicon. For metagenomics the sample id will be the pool identifier and the sample name will be the per sample ID."
    * **Therefore** I judge this suggestion off the table.
* Rob raises the point "user supplied names often don’t meet specs for downstream steps"
    * The bcl2fastq2 guide referenced above states "You can use alphanumeric characters, hyphens [-], and underscores [_] forthe Sample_Project, Sample_ID,
and Sample_Name. Sample_ID, Sample_Name, and Sample_Project field entries in the sample sheet cannot contain illegal characters that are not allowed by some file systems. Examples of common characters that are not allowed are the space character and the following: ?()[]/\=+<>:;"',*^| &."
    * As far as I know, there are currently no constraints in Labman on what the external_id can be, and thus no guarantee it will meet the bcl2fastq2 conditions.
    * As far as I know, there is also no constraint in Labman forcing the external_id to be unique; if we use extenal_ids as the Sample_IDs, and *if* Sample_IDs are used to link sequencing results back to the pools they came from, non-unique names could lead to problems deconvolving sequencing results.

This question is still open.

**Comment by tanaes** [comment]
I'd still suggest leaving the composition_id in the Sample_ID column and
the external_id in the Description column, which has no character
restrictions and would be just as useful for human loading purposes.

**Comment by AmandaBirmingham** [comment]
After extending our discussion with Greg to cover shotgun sample sheets as well, we concluded that many of the same rules formulated above should apply to both amplicon and shotgun sample sheets.  Here are the final specs we decided on today, collected in one place:

1) For both amplicon and shotgun sample sheets:
    * For single-lane sequencers:
        * A "Lane" column will NOT be included in the sample sheet
        * A lane suffix will NOT be added to the relevant Sample_ID
    * For multi-lane sequencers:
        * A "Lane" column WILL be included in the sample sheet
        * A lane suffix (an underscore, plus "L", plus the 1-based number of the lane) will be added to the end of every Sample_ID

2) For amplicon sample sheets ONLY (both single-lane and multi-lane):
    * Sample_ID will be the external_id of the the pool's tube (plus the lane suffix if required--see 1 above)
    * Description will be the pool's composition_id

3) For shotgun sample sheets, both single-lane and multi-lane:
    * The contents of the Sample_ID and Description will remain what they currently are in Labman (**except** for the addition of the lane suffix to Sample_ID if required--see 1 above)

**Comment by tanaes** [comment]
Why add the _Lx to the Sample_ID? It's ok to have a Sample_ID duplicated on
a sample sheet if it is in a separate lane, and the _Lx_ extension will
automatically get added to the sequence file when it is converted to Fastq
by Bcl2fastq.

**Comment by qiyunzhu** [comment]
@tanaes Rob quoted Illumina's explanation: "Single sample sequencers require Sample_ID to be unique per lane same as the others, only have only one lane." So I guess Jon is correct. We should remove that `_Lx` thing. @AmandaBirmingham what do you think?

**Comment by qiyunzhu** [comment]
@AmandaBirmingham Thanks for the feedback! I have updated the code. #268

**Comment by ElDeveloper** [comment]
Fixed in #268
