### ISSUE TITLE
Populate real labman db with needed real equipment/etc records

### ISSUE THREAD

**Issue by AmandaBirmingham** [jdereus/labman#262]
Greg H. pointed out that the list of sequencers available on the Prepare Sequencing Run page in the labman test database is not complete and will need to be added to before soft launch.  There may be other such set-up that needs to be done (see the "Database Preparation" section of labman/db/support_files/labman_DB_schema_description.pdf for a list of the sorts of information that need to be pre-populated before use).

**Comment by tanaes** [comment]
Hi @AmandaBirmingham ,

I'm planning on coordinating with the wet lab to update these things. Are these things that need to be added to the db_patch.sql, or via the equipment addition interface on the running instance?

**Comment by AmandaBirmingham** [comment]
Hi, @tanaes ,
Bringing @antgonza in on this in case he has additional input ...

At the moment, I don't think we have a running instance of the labman db that it would be safe to add real, persistent records to (in part because labman tables are being separated from qiita tables per issue #257 , but also just as far as I know we don't have a "live" labman db yet :) ).  This, I fear, rules out using the equipment interface in the gui.  I should also note that there may be other things that need to be prepopulated (e.g., protocols, reagent composition types, etc per labman/db/support_files/labman_DB_schema_description.pdf) that I don't think can be set up from the gui, although I haven't done an exhaustive search :)

I guess that leaves modifying the sql files.  I see that there are no insert statements whatsoever  db_patch.sql, whereas there *are* insert statements in db_patch_manual.sql; I don't know what the reason is for having two or what difference between them is (except that db_patch.sql is run before db_patch_manual.sql), but I suppose we might want to keep doing it the way it is currently being done and assume there is a good reason.

Rob also floated the idea of creating tables in excel that contain the various records that need to be added and then uploading them into the db; he figured this would make it easier to gather the info and update it in the future.  I fear it would be more trouble than it is worth, especially with the need for foreign key linkages between some of the tables, but that avenue is open to you if you think it best.

**Comment by AmandaBirmingham** [comment]
Oh, @tanaes , also please read new issue #266 ... I'm not asking you (or anyone) to actually work on this issue right now, but it documents a manual code change you will have to make in process.py if you end up adding any new kinds of sequencers to the db.

**Comment by tanaes** [comment]
Ok I'm not sure I understand the scope of what's needed right now then. It seems to me that anything that *can* be added from the web interface *ought* to be, no? 

@josenavas can you comment on the distinction between db_patch.sql and db_patch_manual.sql?

**Comment by AmandaBirmingham** [comment]
Well, if equipment is added from the web interface, then it gets added INTO whatever db is behind that interface.  Right now as far as I know, all the labman dbs we have are just test dbs, not production ones.  Thus, unless we do something to write those new db contents (added to the db from the web interface) out to a sql script that we can then run on some other db, those records will be lost when the test database they were added to is shut down (or cleared by the next run of the unit tests).  Does this clarify?

**Comment by AmandaBirmingham** [comment]
Yes, I see your point re not adding the real records into the base db (especially since adding new records might mean we have to rejigger the unit tests--urgh!)  In that case, rather than adding the info into db_patch_manual.sql, I assume that we would want a new and different sql script--something that is the equivalent of populate_test_db.sql, but is instead called something like "populate_real_db.sql".

**Comment by tanaes** [comment]
That seems plausible to me! When I hear back from the wet lab I'll have
them put together some sort of flat file that we can use to generate the
sql.

**Comment by tanaes** [comment]
I've sent a Google Drive spreadsheet to the wet lab to populate with equipment; it has a type verification to make sure it matches the available equipment types. Once that's filled out we can create an SQL or python function to update the database.

**Comment by antgonza** [comment]
Looking at the code the difference between db_patch.sql and db_patch_manual.sql is that db_patch.sql creates the tables and db_patch_manual.sql populates the tables with the initial values.

**Comment by josenavas** [comment]
Hi - Sorry for my slow reply - got in a motorcycle accident on Tuesday and I've been offline until today - I'm okay just a bit sore :)

so the main difference between db_patch.sql and db_patch_manual.sql is that db_patch.sql is the SQL patch that is automatically generated by DB schema, while db_patch_manual.sql are values and FK that needed to be added manually either to set up the database or because DB schema was unable to generate. There are some values in some tables that are just internal to the DB and are useful to speed up some lookups (e.g. the components type). That is just for speeding up processes and searches.

I decided to keep them separated because that way if changes happen in DB schema we can overwrite the db_patch.sql file w/o worrying about the manual changes.

**Comment by antgonza** [comment]
By @tanaes request I'm putting together a script to read a google doc with all equipment that inserts those values to the DB; just wondering if we should add to the repo and how; @AmandaBirmingham , thoughts? The idea is that the weblab can add new values to that document and the new values will be added.

**Comment by AmandaBirmingham** [comment]
I have no problem with adding the script to the repo.  I assume the script will only insert new values that aren't already in the db, so that when the wet lab adds new values to their doc, the previous values don't get re-assigned new keys.

**Comment by antgonza** [comment]
Kewl! I'll finish up and issue a PR for review ... BTW yes, no duplicated.

**Comment by AmandaBirmingham** [comment]
As discovered in today's initial Labman run against qiita-rc, this needs to include populating the labmanager_access table with the email addresses of qiita users who should have access to labman; without these, no one can log in to labman.

**Comment by antgonza** [comment]
What about a list?
- [ ] emails of users, should this be added to the same script
- [ ] equipment and equipment_type

Note that in general we just add these kind of information directly in the database once is deployed, cause in reality, once it's deployed for real, it should only be loaded once. Thoughts?

**Comment by AmandaBirmingham** [comment]
Just to capture my comments from the mtg: I have no investment in having these real records captured in a documents directly accessible by the lab. As mentioned above (https://github.com/jdereus/labman/issues/262#issuecomment-407842994) re using non-script options like files/spreadsheets/etc, "I fear it would be more trouble than it is worth, especially with the need for foreign key linkages between some of the tables, but that avenue is open to you if you think it best."

As long as the real records get captured in some persistent form, and as long as we can put that track versions of that persistent form (such as by putting it into the repository), and as long as loading those records to the db works,  I am on board :)

**Comment by AmandaBirmingham** [comment]
By the way, please note again that the real records needed are not limited to just users and equipment/equipment types.  Per my comment in opening this issue (https://github.com/jdereus/labman/issues/262#issue-344218007) "There may be other such set-up that needs to be done (see the "Database Preparation" section of labman/db/support_files/labman_DB_schema_description.pdf for a list of the sorts of information that need to be pre-populated before use)."  https://github.com/jdereus/labman/blob/master/labman/db/support_files/labman_DB_schema_description.pdf

**Comment by rob-knight** [comment]
To clarify: I think it’s important the wet lab enters the data, hence spreadsheet not looking directly at sql code. However, I don’t think they need to be able to continue to update the spreadsheets live because we hope not to reload the database _that_ often.

@tanaes, can you confirm all the data from the docs linked by @AmandaBirmingham are in the spreadsheets already? If yes, @antgonza, you can set up the load by whatever method is most convenient. Thanks.

**Comment by AmandaBirmingham** [comment]
I think that one of the issues collected earlier this week while walking through the Labman amplicon workflow with the wet lab is in fact a component of this issue:

https://github.com/jdereus/labman/issues/288 Add 18S and ITS primer plates to Prepare Amplicon Libraries

It appears that the wet lab now needs more primer sets to be defined in the db than are added by the current version of db_patch_manual.sql.
