### ISSUE TITLE
Check more than the first component of PoolComposition when determining type of contents

### ISSUE THREAD

**Issue by AmandaBirmingham** [jdereus/labman#267]
In labman.db.composition.PoolComposition.get_components_type, the code checks the type of ONLY the first component of the pool and then assumes all the rest are the same.  As far as I know, there is not a logical constraint that forces this to be the case, so I think we should probably check the entire set.

**Comment by wasade** [comment]
In #414, I took the more conservative approach which was to assert only a single composition type is present. I have zero idea of what would be needed downstream to support multiple composition types.

**Comment by AmandaBirmingham** [comment]
I checked the usages of this method in the codebase, and I agree that erroring if all component types aren't the same should be fine.
