### ISSUE TITLE
decide how to create cookie_secret

### ISSUE THREAD

**Issue by antgonza** [jdereus/labman#276]
cookie_secret is the "key" to generate sessions and currently is random, which is a problem if we want to have multiple tornado workers as all of them should have the same one. Thus, I foresee 2 options: use the same one than qiita or separate; this depends on https://github.com/jdereus/labman/issues/275.

Note that the implementation is the same but the difference of the options is the value that goes into that configuration variable.

**Comment by antgonza** [comment]
As labman is gonna be a different url, we can leave as random right now but this will come back if we need to start different workers. Thus, leaving open but removing from #263 and making low priority

**Comment by AmandaBirmingham** [comment]
Also see related issue #223 Mutually exclusive login between labman and qiita
