### ISSUE TITLE
Do not auto-fill plate names, or else make it clearer user needs to notice their values

### ISSUE THREAD

**Issue by AmandaBirmingham** [jdereus/labman#287]
Raised in amplicon walkthrough 07/30/2018

**Comment by AmandaBirmingham** [comment]
Some users seemed to like the auto-filling but wanted to adjust the names:
"Might be nice to have it "Shotgun library" instead of Shotgun" 
Raised in shotgun walkthrough 07/31/2018

**Comment by charles-cowart** [comment]
It seems like the wet-lab is fairly comfortable with how plate names are entered, currently. Taking this off the board, as it appears self-evident that the wet-lab is validating the plate-names on entry.
