### ISSUE TITLE
Add calculation of concentration from fluorescent units 

### ISSUE THREAD

**Issue by AmandaBirmingham** [jdereus/labman#290]
Raised in amplicon walkthrough 07/30/2018
Currently the platereader used measures relative fluorescent units
Jon created program that changes relative fluorescent units to concentration based on a ladder 
Unclear exactly where program is housed (in platereader, in computer connected to platereader, something like that)
Right now labman expects uploaded file to hold concentration
For the moment, lab can work with existing functionality (concentration file required) but they have to use Jon's program to convert first

**Comment by tanaes** [comment]
Rodolfo created a program for the plate reader to automatically calculate
concentration (same as is used for shotgun), please also check with him on
this.

**Comment by charles-cowart** [comment]
Will check in w/Rodolfo and determine if the current intention is to maintain this separately or assimilate into LC.

**Comment by charles-cowart** [comment]
Greg and Rodolfo confirm that there is a current benefit to using the external program as an independent check. Having the external program calculate the regression curve and concentrations also allows other potential LC users to have the freedom to use other software for this.
