### ISSUE TITLE
Update amplicon sample sheet with currently used values

### ISSUE THREAD

**Issue by AmandaBirmingham** [jdereus/labman#296]
In [Header]:
Change value associated with "Assay" from "Amplicon" to "TruSeq HT"
Change value associated with "Chemistry" from "Default" to "Amplicon"
In [Settings]:
Add "Adapter" field and appropriate value as DNA
Add "AdapterRead2" field and appropriate value as DNA
(Scope of this issue includes FINDING OUT from wet lab what the appropriate values are and figuring out where to get the in Labman db).
In [Data]:
Check with Greg whether I5_Index_ID and index2 fields should be added to output (after index column)
Note: do NOT change "Well_Description" back to "Description" : Gail Ackermann requested this change as part of PR 268. 

Raised in amplicon walkthrough 07/30/2018

**Comment by AmandaBirmingham** [comment]
Per Greg Humphrey: "The adapters are always the same and are located on our primers" and "the adapters are the same for 16S, 18S, and ITS".  Thus, the values for Adapter and Adapter2 will be the same in every amplicon sample sheet, regardless of primer set, etc.

**Comment by qiyunzhu** [comment]
Hi @AmandaBirmingham I have tackled this issue. See PR #318 . I talked with Greg and understood their requirement in the sample sheet format.
