### ISSUE TITLE
Update generation of Preparation Sheets contain correct columns/values

### ISSUE THREAD

**Issue by AmandaBirmingham** [jdereus/labman#301]
Raised in amplicon walkthrough 07/30/2018
Note: below, "(empty)" means this column is intentionally left empty. "(empty)" is NOT part of the column name.

sample_name
BARCODE
PRIMER
Primer_Plate
Well_ID
Plating
ExtractionKit_lot
Extraction_robot
TM1000_8_tool
Primer_date
MasterMix_lot
Water_Lot
Processing_robot
TM300_8_tool
TM50_8_tool
Sample_Plate
Project_name
Orig_name
Well_description
EXPERIMENTAL_DESIGN_DESCRIPTION
LIBRARY_CONSTRUCTION_PROTOCOL
LINKER
PLATFORM
RUN_CENTER
RUN_DATE (empty)
RUN_PREFIX (empty)
pcr_primers
sequencing_meth
target_gene
target_subfragment
center_name
center_project_name (empty)
INSTRUMENT_MODEL (empty)
runid (empty)

**Comment by AmandaBirmingham** [comment]
Hi @qiyunzhu : This issue will require modifying the `generate_prep_information` method in labman/db/process.py , specifically the part for Amplicon prep info generation.  You can see an example of what the current output looks like in the `TARGET_EXAMPLE` constant in labman/db/tests/test_process.py .  However, the wet lab indicates they are expecting it to have a different set of column names/order, etc than it currently creates.  I will email you the correct example directly.

**Comment by qiyunzhu** [comment]
Hi @AmandaBirmingham I explored the header names and still wasn't sure how to start with. First, I wonder if there is a mapping between old and new names? I guess `MasterMix_lot` is identical to `master_mix`, but I don't know if `kingfisher_robot` and `Processing_robot` are the same thing. Second, the new list of header names is longer and new columns need to retrieved by modifying the SQL command. It will be great to know where they are stored in the database. Some seem to be hardcoded I guess (e.g., `target_gene` == `16S rRNA`). My limited understanding of SQL language and labman database structure may make this task bit challenging. So I probably will need lots of help from you...

**Comment by qiyunzhu** [comment]
This is the best I can guess. Many columns are missing from the original report.

new | old | empty | uncertain
-- | -- | -- | --
sample_name | sample_name |   |  
BARCODE | primer_set_composition |   | ?
PRIMER |   |   |  
Primer_Plate |   |   |  
Well_ID | well |   |  
Plating |   |   |  
ExtractionKit_lot | extraction_kit |   |  
Extraction_robot | kingfisher_robot |   |  
TM1000_8_tool | epmotion_tool |   | ?
Primer_date |   |   |  
MasterMix_lot | master_mix |   |  
Water_Lot | water_lot |   |  
Processing_robot | gdata_robot |   |  
TM300_8_tool | epmotion_tm300_8_tool |   |  
TM50_8_tool | epmotion_tm50_8_tool |   |  
Sample_Plate | plate |   |  
Project_name |   |   |  
Orig_name |   |   |  
Well_description |   |   |  
EXPERIMENT_DESIGN_DESCRIPTION |   |  
LIBRARY_CONSTRUCTION_PROTOCOL |   |  
LINKER |   |   |  
PLATFORM | platform |   |  
RUN_CENTER |   |   |  
RUN_DATE |   | yes |  
RUN_PREFIX | run_prefix | yes |  
pcr_primers |   |   |  
sequencing_meth |   |   |  
target_gene |   |   |  
target_subfragment |   |   |  
center_name |   |   |  
center_project_name | center_project_name | yes |  
INSTRUMENT_MODEL |   | yes |  
runid |   | yes |

**Comment by AmandaBirmingham** [comment]
Thanks to @qiyunzhu 's investigation and subsequent conversations with Gail and Greg, it is clear that the current preparation sheet generation code is producing outputs that are quite different in format and content from what the current known-good processes generate.  It will be necessary to non-trivially alter the code in process.py to address this.

**Comment by antgonza** [comment]
Taking a look into this now. Just a couple of things to confirm:
1. Basically we want to make sure that we have the list of columns in the table above and in that order, right?
2. This only applies for TARGET_EXAMPLE / amplicon, right?

**Comment by antgonza** [comment]
More on 1, if we only need to change the column/values we have to options:
A. rename the columns in the dataframe + create the new empty ones also there.
B. add/rename in the database

A is much simpler and quicker (a patch) and will need confirmation from @AmandaBirmingham to see if this is fine.

BTW, the Amplicon/TARGET_GENE dataframe column names are:
```
Index(['gdata_robot', 'extraction_kit', 'epmotion_robot',
       'sequencer_description', 'kingfisher_robot', 'epmotion_tm50_8_tool',
       'run_name', 'experiment', 'platform', 'rev_cycles', 'master_mix',
       'well', 'principal_investigator', 'water_lot', 'epmotion_tool',
       'fwd_cycles', 'plate', 'run_prefix', 'center_project_name',
       'primer_set_composition', 'epmotion_tm300_8_tool',
       'primer_composition'])
```
And the Shotgun:
```
Index(['gdata_robot', 'extraction_kit', 'sequencer_description',
       'kingfisher_robot', 'run_name', 'experiment', 'platform', 'rev_cycles',
       'well', 'principal_investigator', 'normalization_water_lot',
       'run_prefix', 'epmotion_tool', 'plate', 'i5_sequence',
       'center_project_name', 'fwd_cycles', 'stub_lot',
       'kappa_hyper_plus_kit'])
```
