### ISSUE TITLE
Fix missing display of concentration histogram

### ISSUE THREAD

**Issue by AmandaBirmingham** [jdereus/labman#309]
Raised in shotgun walkthrough 07/31/2018

**Comment by tanaes** [comment]
Hi Amanda, can you describe what situations these are not showing in? I’m en route to France right now and don’t have much of any bandwidth, but something might ring a bell.

**Comment by AmandaBirmingham** [comment]
Hi @tanaes Thanks!  This one was labeled as necessary for soft launch because we saw it during the shotgun walkthrough (so, theoretically, on real data) but I am suspicious that it may have been instigated by other hacks we had to do to work with the real data at that point.  Since then, the only situation in which I can reproduce is it is if I attempt to quantify a plate that is ALL blanks (but for which I uploaded real, nonzero concentration data), as shown in this example:

![screen shot 2018-08-15 at 12 35 29 pm](https://user-images.githubusercontent.com/10677935/44171496-32ed9a80-a08f-11e8-8de8-938d3c81cab4.png)

**Comment by tanaes** [comment]
Hmm, doesn’t ring a bell. @eldeveloper wrote the JavaScript plotting
function for this, but my guess is that because it’s explicitly looking for
blanks and samples, if it’s not finding one of those categories it’s
throwing an error?

**Comment by ElDeveloper** [comment]
From some testing online, this seems to be a bug with Plotly failing to render the histogram if one of the two traces is empty. Seems to be fixed in the latest version so this might be as easy as updating the library version

**Comment by AmandaBirmingham** [comment]
Oh yeah, give it up for @ElDeveloper !  Updating to plotly 1.40.0 gives this: 

![screen shot 2018-08-21 at 2 42 31 pm](https://user-images.githubusercontent.com/10677935/44430770-9a549000-a550-11e8-94f1-8d9c641a7e5c.png)

Still missing a legend (as shown in example below of a plate that ISN'T all blanks) but since an all-blanks plate is a pathological example and since (even without a legend on the histogram) it is clear from the per-well concentration graph above that *all the wells are blanks*, I'm going to let that one go :)

![screen shot 2018-08-13 at 11 34 47 am](https://user-images.githubusercontent.com/10677935/44430858-e0a9ef00-a550-11e8-804f-4c49b24910b4.png)
