### ISSUE TITLE
Correct name of key file attribute of ConfigurationManager in start-up script

### ISSUE THREAD

**Issue by AmandaBirmingham** [jdereus/labman#315]
```
(labman) Amandas-MacBook-Pro-4:labman Birmingham$ labman start_webserver
Traceback (most recent call last):
  File "/Users/Birmingham/Applications/miniconda3/bin/labman", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/Birmingham/Work/Repositories/Labman/labman/scripts/labman", line 100, in <module>
    labman()
  File "/Users/Birmingham/Applications/miniconda3/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/Birmingham/Applications/miniconda3/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/Birmingham/Applications/miniconda3/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Birmingham/Applications/miniconda3/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/Birmingham/Applications/miniconda3/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/Birmingham/Work/Repositories/Labman/labman/scripts/labman", line 43, in start_webserver
    'keyfile': labman_settings.keyfile}
AttributeError: 'ConfigurationManager' object has no attribute 'keyfile'
```
The attribute in question is now named `key_filepath`.

**Comment by antgonza** [comment]
Just hit this during deploy in labman-rc, saw the fix in the commit (thanks!) and makes sense but can you also add a call to labman in .travis.yml so we can catch this error? Something like this to the end of the tests:
```
labman &
LABMAN_PID=$!
sleep 5 # or 10?
kill $LABMAN_PID
```

**Comment by AmandaBirmingham** [comment]
Will do!  I have a teeny fix branch ready to push to a PR, so I’ll add this in before I make it a PR and then ask you to review :)

**Comment by qiyunzhu** [comment]
I got blocked by the same issue after git pull latest master branch... Looking forward to a solution.

**Comment by qiyunzhu** [comment]
Hi @AmandaBirmingham and @antgonza , currently I cannot launch labman, even after I changed `keyfile` into `key_filepath`. When I did `labman start_webserver` there was no error message, but when I browsed `localhost:8080`, nothing showed up.

Is there a simple fix to this situation, or should I be patient for the next patch? Thank you!

My `~/.labman.cfg` is as follows:
```
# Configuration file generated by labman on 2018-08-08 09:32:29.279823

# ------------------------- MAIN SETTINGS ----------------------------------
[main]
TEST_ENVIRONMENT=True
LOG_DIR=/tmp/
CERTIFICATE_FILEPATH=/Users/qiz173/Desktop/Sidejects/LabMan/labman/support_files/server.crt
KEY_FILEPATH=/Users/qiz173/Desktop/Sidejects/LabMan/labman/support_files/server.key

# ----------------------- POSTGRES SETTINGS --------------------------------
[postgres]
USER=postgres
PASSWORD=
ADMIN_USER=postgres
ADMIN_PASSWORD=
DATABASE=qiita_test
HOST=localhost
PORT=5432

# ------------------------- QIITA SETTINGS ----------------------------------
[qiita]
SERVER_CERT=/Users/qiz173/Desktop/Sidejects/LabMan/qiita/qiita_core/support_files/server.crt
```

**Comment by antgonza** [comment]
The fix is quite simple, just replace this line:
https://github.com/jdereus/labman/commit/4407f327c6607db5ff775d4e17bac3d165d17bba#diff-df5a804a8c18fa04f0e9918099691ae9R43

Note that @AmandaBirmingham has a PR fixing it.

**Comment by AmandaBirmingham** [comment]
Did you (a) make the certificate and (b) browse to httpS instead of http?

On Aug 8, 2018, at 9:39 AM, Qiyun Zhu <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @AmandaBirmingham<https://github.com/AmandaBirmingham> and @antgonza<https://github.com/antgonza> , currently I cannot launch labman, even after I changed keyfile into key_filepath. When I did labman start_webserver there was no error message, but when I browsed localhost:8080, nothing showed up.

Is there a simple fix to this situation, or should I be patient for the next patch? Thank you!

My ~/.labman.cfg is as follows:

# Configuration file generated by labman on 2018-08-08 09:32:29.279823

# ------------------------- MAIN SETTINGS ----------------------------------
[main]
TEST_ENVIRONMENT=True
LOG_DIR=/tmp/
CERTIFICATE_FILEPATH=/Users/qiz173/Desktop/Sidejects/LabMan/labman/support_files/server.crt
KEY_FILEPATH=/Users/qiz173/Desktop/Sidejects/LabMan/labman/support_files/server.key

# ----------------------- POSTGRES SETTINGS --------------------------------
[postgres]
USER=postgres
PASSWORD=
ADMIN_USER=postgres
ADMIN_PASSWORD=
DATABASE=qiita_test
HOST=localhost
PORT=5432

# ------------------------- QIITA SETTINGS ----------------------------------
[qiita]
SERVER_CERT=/Users/qiz173/Desktop/Sidejects/LabMan/qiita/qiita_core/support_files/server.crt

**Comment by qiyunzhu** [comment]
Hello @AmandaBirmingham and @antgonza I already did the fix Antonio pointed to. I made a certificate using the command provided in readme, and browsed `https://localhost:8080/`. They didn't work, though.

**Comment by qiyunzhu** [comment]
Hi all, this issue was resolved on my machine, after I did `python labman/db/tests/test_sql_connection.py`. I don't know why though.
