### ISSUE TITLE
Include database permission requirements in install directions

### ISSUE THREAD

**Issue by AmandaBirmingham** [jdereus/labman#358]
The current install directions will not produce a working labman install unless the supplied database user is granted permissions to the labman database.  Incorporate the info @jdereus  provided about how to do this into the install document:

Create user labman
Alter user labman with encrypted password ‘<password here>’;
 
Grant select on all tables in schema qiita to labman;
 
As labman should not have create permissions on db, the labman patch scripts will be run as postgres.  This gives odd ownerships that need to be modified.
 
-bash-4.2$ SCHEMA=labman
-bash-4.2$ DB=qiita
-bash-4.2$ for table in `psql -tc "select tablename from pg_tables where schemaname = '${SCHEMA}';" ${DB}` ; do psql -c "alter table ${SCHEMA}.${table} owner to labman" ${DB}; done
 
Grant all on all tables in schema labman to labman;

Also, point out that when starting the labman server, if it should be started on any port other than the default port of 8080, the user needs to run start_webserver specifying the optional `--port` switch, e.g. `--port 5555`.

**Comment by antgonza** [comment]
I'll argue that this is specific to the actual deploy cause if "The current install directions will not produce a working labman install" we couldn't run tests in travis ... I mean, each deploy will be contingent to the will of the sys admin but the instructions are correct based on the test environment of qiita and labman ...
