### ISSUE TITLE
Upgrade command-line command names to work with click library version 7

### ISSUE THREAD

**Issue by AmandaBirmingham** [jdereus/labman#359]
The labman.py and db/tests/tester.py scripts use the click library to create command-line command names.  The click library has just released a new major version, which now automatically changes command names with underscores to have dashes instead unless you specifically set the name, and this causes the travis build script to fail because some of the commands are not found:

![screen shot 2018-10-03 at 11 27 48 am](https://user-images.githubusercontent.com/10677935/46430969-6ba90800-c6ff-11e8-87ea-0d6677f87bac.png)

I guess this is a bug ... now ... https://github.com/pallets/click/issues/1123

**Comment by antgonza** [comment]
Yup, 2 options: fix the click version or change the command names ... I don't have a preference.
