### ISSUE TITLE
Change prep info file generation to include info on all wells from library prep plate, regardless of whether they are pooled

### ISSUE THREAD

**Issue by AmandaBirmingham** [jdereus/labman#381]
While the existing code works as it was written to do, there is a *conceptual* bug in the prep info file produced by Labman versus that produced by the current process.  The Labman prep info file includes ONLY those samples/wells that were actually sequenced in the run (which is consistent with the prep info file including fields about what machine the sample was run on, etc). However, the current process prep info file includes info on EVERY well on the input plates, even if those wells were not actually included in the pool that was sequenced (and also includes columns saying those wells were sequenced on x machine, etc).  In practice, this difference manifests for blanks, because only 2 blanks from each plate are actually included in the amplicon pool for that plate.

Per Gail 10/09/2018: every well on the library prep plate(s) used in the run goes into the prep sheet, regardless of whether it was pooled.  Show which ones were actually pooled by adding a new column `was_pooled` (boolean).

Per Gail 10/31/2018: 
I have already started the study for blanks and it is set up in the same way as the AGP study with a prep for each run.  So all of the blanks from a single pool (no matter how many projects) are in the same prep - both pooled and not pooled.  So Labman (or whatever moniker they choose to call it by) should output a prep for the blanks - not sure if it should reference the study ids the actual projects are associated with the blanks.

**Comment by AmandaBirmingham** [comment]
Doing this requires changing the whole concept behind the gigantic sql statement driving the prep sheet creation.  It will take a bit of effort.

**Comment by josenavas** [comment]
Sorry to jump in, but, is this actually correct? If the well was not pooled then there is nothing on the final sequencing for it (since the source well was not touched when pooling).

I may be missing some background, but as per Gail in 10/31/2018 listed above, it looks like there is some kind of study for blanks. That's okay, but referencing my previous point, there is a _conceptual_ difference between blanks and unused wells (those that are not pooled).

Also, this becomes even more clear on shotgun since the wells are cherry picked. Maybe I'm out of bounds, but given the scope of the issue it may be worth to double check with some wet lab folks.

**Comment by AmandaBirmingham** [comment]
I have double checked, because I had the exact same concern—wth, why include wells that are on the library prep plate but *aren’t pooled* in the prep file for the sequencing of a pool?!  The answer, I have been informed by Gail, and Greg, and Rob, is that *sometimes* there are reads found for the barcodes associated with those those theoretically-not-pooled wells—which means either there was contamination (from splashing, etc) in the actual pooled wells, or else (as I’m told has in fact happened) the plate was rotated at some point in handling so that instead of e.g. pooling an experimental sample in well A1, they instead pooled a blank in well H12.

On Nov 7, 2018, at 7:43 AM, Jose Navas <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry to jump in, but, is this actually correct? If the well was not pooled then there is nothing on the final sequencing for it (since the source well was not touched when pooling).

I may be missing some background, but as per Gail in 10/31/2018 listed above, it looks like there is some kind of study for blanks. That's okay, but referencing my previous point, there is a conceptual difference between blanks and unused wells (those that are not pooled).

Also, this becomes even more clear on shotgun since the wells are cherry picked. Maybe I'm out of bounds, but given the scope of the issue it may be worth to double check with some wet lab folks.

**Comment by josenavas** [comment]
Ouch X.X - Thanks for the extended explanation! It is good to have it here anyways for future reference, since this is not easily deducible from what one would expect. That really breaks a bit the current SQL...

In order to reduce the scope, it may be useful to perform 2 queries instead of a single one (the second one being to recover only the blanks information). That will leave the current query intact and the addition of 1 SQL query shouldn't impact that run time dramatically.

**Comment by AmandaBirmingham** [comment]
While working on this issue, I found that at some point in the history of this SQL statement, it acquired two bugs: although there are selected values that are being *named* "plating" and "primer_date", they are not actually the personnel id of the person doing the plating and the date that the primer working plate was created (as they are intended to be).  Rather, they are the personnel id of the person who prepared the sequencing run, and the date of that run preparation :(  I'll be fixing these as part of this issue.

**Comment by AmandaBirmingham** [comment]
Found another nasty little bug in the sql that creates the prep sheet:

                 LEFT JOIN labman.composition c4 ON (
                    lp.primer_composition_id = c4.composition_id
                )

where `lp` is the `labman.library_prep_16s_composition` table.  This looks ok at first glance, but from `db_patch.sql` (see below), we know that the `primer_composition_id` column in this table is a foreign key to the `labman.primer_composition` table, NOT the `labman.composition` table!  Thus, the existing sql is essentially picking a composition id at random (not actually the composition id associated with the primer being used) and following it backwards to get the plate it came off of.  

We never noticed this before because the unit tests depend sensitively on the test database, and the unit test database has some regularities that cannot be depended on in real data due to its records being the very first added to database (and in a very structured way).  In this case, the `primer_composition_id`s for the first four plates-worth of `library_prep_16s_composition`s are numbered 1-380 (remember, each plate has one empty, so not 384)--and `composition_id`s 1-380 just happen, based on how we set up the database-population scripts, to be the composition ids of the compositions for the first four EMP 16S V4 primer plates ... which are what we expected, so we never noticed the problem :( :(

Again, will fix this as part of this issue.

`ALTER TABLE labman.library_prep_16s_composition ADD CONSTRAINT fk_16s_library_prep_composition_primer FOREIGN KEY ( primer_composition_id ) REFERENCES labman.primer_composition( primer_composition_id );`

**Comment by wasade** [comment]
That is a very good catch. Do you think it is necessary for us to take a close review of other queries for these type of inconsistencies?

**Comment by AmandaBirmingham** [comment]
I think that would be a great idea but is probably not critical enough to hold up soft launch.  I say this because I believe the issue I found above would very likely have become obvious when generating prep sheets against real data/records in a production-like db--especially when compared to the results of the current process--so I think it would have led to BS results that someone called out, rather than BS results that were silently accepted.

**Comment by AmandaBirmingham** [comment]
I have broken the request for a new field (`was_pooled`) out of this issue and into a new feature request issue (#387) since it would be adding new functionality rather than reproducing the existing wet-lab functionality.
