### ISSUE TITLE
Ensure normpool file generation is correct

### ISSUE THREAD

**Issue by AmandaBirmingham** [jdereus/labman#382]
This MAY be a bug or maybe not.  The normpool file created by Labman is producing different concentrations than those in the expected gold standard file when using the directions in the real-test readme (attached)
[README.txt](https://github.com/jdereus/labman/files/2555587/README.txt) .  Per discussion with Rodolfo, it is plausible that this is NOT due to a bug but rather to the inputs in the README not being the correct ones that were used to generate the gold standard file.  Need to work with Rodolfo to determine whether there is a plausible set of inputs that, when fed into Labman, produces the expected output concentrations.

![shotgun_pool_file_differences](https://user-images.githubusercontent.com/10677935/48102581-9a277080-e1e0-11e8-864b-5e858d8635ad.png)

**Comment by AmandaBirmingham** [comment]
@charles-cowart @wasade @ElDeveloper I learned this morning that Rodolfo is out for 2 weeks, which rather scuttles the plan Charlie and I discussed on Friday of walking through this with Rodolfo to see if he could guess whether other likely inputs exist that would give the outputs we got from labman.  I do not know whether there is another person in the wetlab who could step in for this checking--do any of you?

Given the investigation above (and given the fact that I know for sure that the inputs the wet lab gave me for some of the steps in the *amplicon* real-data test were NOT actually the inputs they used to create the output files they gave me :-/   ), I feel fairly confident (85%?) that the normpool calculations are working as they are supposed to do.  I also believe that if they aren't, we will see that just about immediately after soft launch because the wet lab will be running their existing process alongside labman--and hopefully entering the same inputs into each!--so if the normpool files don't match, they will see that as soon as they are created.

Given this, I lean towards NOT blocking soft launch until we have a chance to chase this issue further if no one knowledgeable in the wet lab is available to do so this week.  What do you folks think?

**Comment by charles-cowart** [comment]
I agree. It hasn’t been clearly demonstrated that it’s not operator error.
In either case, I can try to demonstrate the patterns Amanda has seen
programmatically, instead of talking to Rodolfo. I wouldn’t hold soft
launch up for this.

**Comment by wasade** [comment]
I also think this does not warrant a block of soft launch: it is our understanding the notebook is correct. Is it possible the known good file was produced _prior_ to the establishment of the notebook? 

@tanaes may have additional insight here.

**Comment by AmandaBirmingham** [comment]
Since we have decided to go to soft launch without doing this, I believe the purpose it was intended to serve will be filled by the soft launch real-time checks.  I am therefore closing this a wontfix.
