### ISSUE TITLE
Modify Sample Plate and Sample Well sources on sample sheet

### ISSUE THREAD

**Issue by AmandaBirmingham** [jdereus/labman#384]
Per Greg 10/09/2018: 
Sample_Plate should actually be name of sample plate--not extracted, not compressed, etc, but
sample_well should come from COMPRESSED plate

**Comment by AmandaBirmingham** [comment]
Need to check on scope of this; hopefully not as large as #381 but could turn out to have similar issues.

**Comment by wasade** [comment]
Hopefully this doesn't have the breadth of #381

**Comment by AmandaBirmingham** [comment]
Sadly, this one is not addressed by 381--that one only changes the prep sheet.  But I'm at work on this one right now :)

**Comment by AmandaBirmingham** [comment]
I noticed that implementing this issue means the labman output would be DIFFERENT than the known good for the real-data test.  I therefore checked with Greg, who confirmed that the changes requested in this issue ARE the ones he wants and that he is ok with the labman output being different than the known-good:

From: Greg Humphrey
Date: Tuesday, November 13, 2018 at 12:11 PM
To: "Birmingham, Amanda"
Subject: Re: Brief question about desired contents of shotgun sample sheet

Hi Amanda, 

That is great to hear, looking forward to it!

You are correct we would like to use Example A.  The sample sheet Rodolfo sent you is an old one and that used to be the way that we were tracking things.  However, it led to issues so now we are tracking things just like you mentioned in Example A.

Thanks,
Greg

On Tue, Nov 13, 2018 at 11:48 AM Birmingham, Amanda wrote:
Hi, Greg,
I’m working on making the changes to Labman outputs that were requested in our meeting in early October, and I’m worried I may have mis-recorded or mis-understood one of them.  Could you please read over the below explanation and let me know whether you want the Sample_Plate and Sample_Well columns in the shotgun sample sheets to look like example A or example B?
 
We are trying to get to soft launch by Monday—and it is actually plausible that we might, for the first time ever :)—so I would love to hear back from you as soon as you have a chance.
Thanks,
Amanda
 
For the shotgun sample sheet, my notes say that you want the “Sample_Plate” column to contain the name of the *original 96-well sample plate* that the sample came off of  (not the gdna extracted plate, not the compressed gdna plate, etc) but you want the “Sample_Well” to contain the well of that sample on the *compressed gdna plate*.  For example, in the Salk Ting II experiment that I’m using for my real-data test, that means that these fields might look like 
 
Example A:
 
Sample_Plate                     Sample_Well
Salk_Ting_II_1                   K8
Salk_Ting_II_2                   N3
 
 
However, the sample sheet I got from Rodolfo for the Salk Ting II experiment, which I have been using as the known-good example that Labman should reproduce, has the name of the *compressed gdna plate* in the Sample_Plate column—e.g., 
 
Example B:
 
Sample_Plate                     Sample_Well
Salk_Ting_II_1-4               K8
Salk_Ting_II_1-4               N3
 
Which way do you want labman to do it?
