### ISSUE TITLE
Change "labman" to "labcontrol" in developer-facing files

### ISSUE THREAD

**Issue by AmandaBirmingham** [jdereus/labman#394]
See related issues  #175 Decide on new name to replace labman and #393 Change "Labman" to "LabControl" in user interface.

**Comment by charles-cowart** [comment]
Made a pass replacing all instances of 'labman' and 'Labman' in the code with 'lab control' and 'Labcontrol', respectively. Changes have been pushed to 'Issue394' branch. Will flake8 before creating a PR.

For now, the reference to Jeff's GitHub project 'jdereus/labman' has been kept, until a new home for the project can be determined.

**Comment by charles-cowart** [comment]
We'll need to make sure the labman references in https://github.com/jdereus/labman/blob/master/docs/index.rst are changed as well, since they're being used as the Help menu docs in LabControl.

**Comment by charles-cowart** [comment]
Just to keep track, https://github.com/jdereus/labman/pull/459 also touched on this issue.

**Comment by charles-cowart** [comment]
https://github.com/jdereus/labman/pull/534 Also touches on this issue.

**Comment by AmandaBirmingham** [comment]
@charles-cowart  AFAIcan tell, the only place "labman" is left is in the name of our repo :)  Should we close this issue, or modify it to address the repo name itself?

**Comment by charles-cowart** [comment]
Yeah, I've been thinking the same thing. I think only Jeff has ownership of
the repo; with that and other considerations it's a reasonable task just by
itself.

**Comment by charles-cowart** [comment]
Closing this issue, as #534 removes all remaining instances of labman, save for the github project name itself. A new issue will be created for this migration.
