### ISSUE TITLE
Migrate Labcontrol to use latest Qiita

### ISSUE THREAD

**Issue by charles-cowart** [jdereus/labman#398]
Looking at the Travis file, it appears Labman's unit tests rely on an archived version of Qiita to test install. It would be best to have the Travis file reference the current Qiita Master.

**Comment by antgonza** [comment]
I would say that it should point to dev. Remember all new changes go to qiita-dev and once ready they are pushed to main; thus, there is no assurance that what works in master will work in dev and later in master (after a release). Another option is to build against both. My 2 pesos.

**Comment by charles-cowart** [comment]
Closing as a non-issue, as it's been accepted practice to build off of Qiita dev branch
