### ISSUE TITLE
unable to copy/paste values into sheet

### ISSUE THREAD

**Issue by jdereus** [jdereus/labman#42]
try to copy from another spreadsheet it puts all the text into one cell.  need this function since often will receive the samples in a certain order that matches the metadata and it saves a lot of time and prevents errors when can just copy from the metadata instead of typing in each sample.

**Comment by josenavas** [comment]
After discussing with the wet lab -> right click paste column and paste plate should work.

**Comment by josenavas** [comment]
@ElDeveloper will be working on this.
