### ISSUE TITLE
Prepare Amplicon Sequencing Pool allows user to add metagenomics (not amplicon) plate pools, which leads to error downstream in sequencing run sample sheet preparation

### ISSUE THREAD

**Issue by charles-cowart** [jdereus/labman#420]
Note: The original issue described in this comment, "Download Preparation Sheets button producing junk output" is a duplicate of https://github.com/jdereus/labman/issues/444 and has already been diagnosed there.  I have therefore changed the name of this issue to reflect the *sample sheet* related concerns raised in the comments.

-----------------------------------------------------------------------
Sequence Run List page has a 'download preparation sheets' button, which when pressed is initiating a download procedure for an invalid zip file 22 bytes long. Adjacent button for sample sheets is behaving correctly.

This appears specific to 'HNRC_HIV_4'. The other download preparation sheets buttons work as intended. 

Investigate the cause of this issue.

**Comment by wasade** [comment]
Unsure if related, but it is possible to add plates for sequencing that don't appear to have been normalized. It seems that the plates listed are not assured to be valid. Note that, for recreation, I'm adding plates that were created following the name duplication in #479 -- that may or may not be related. It seems that downloading a sample sheet is possible when using one of the test pools. 

![sample_sheet_exception](https://user-images.githubusercontent.com/474290/56619418-51227780-65da-11e9-9031-7194b336111f.gif)


```bash
AN ERROR HAS OCCURED!
Please copy the following into an issue in our github repository

Error
'PoolComposition' object has no attribute 'normalized_gdna_composition'

Traceback
Traceback (most recent call last): 
File "/Users/dtmcdonald/miniconda3/envs/labcontrol/lib/python3.7/site-packages/tornado/web.py", line 1697, in _execute result = method(*self.path_args, **self.path_kwargs) 
File "/Users/dtmcdonald/miniconda3/envs/labcontrol/lib/python3.7/site-packages/tornado/web.py", line 3174, in wrapper return method(self, *args, **kwargs) 
File "/Users/dtmcdonald/ResearchWork/software/labman/labcontrol/gui/handlers/process_handlers/sequencing_process.py", line 59, in get text = process.generate_sample_sheet() 
File "/Users/dtmcdonald/ResearchWork/software/labman/labcontrol/db/process.py", line 3240, in generate_sample_sheet return self._generate_shotgun_sample_sheet() 
File "/Users/dtmcdonald/ResearchWork/software/labman/labcontrol/db/process.py", line 3078, in _generate_shotgun_sample_sheet compressed_gdna_composition = libprepshotgun_composition.\ 
AttributeError: 'PoolComposition' object has no attribute 'normalized_gdna_composition' 
```

**Comment by wasade** [comment]
One more note here, an implication here is that a sequencing run can be created, and gets added into the list of sequencing runs, even if it is not actually possible to download the sample sheet. So in the screenshot below, IDs 194-199 are invalid as the sample sheet cannot be downloaded. 

<img width="1133" alt="Screen Shot 2019-04-23 at 3 30 46 PM" src="https://user-images.githubusercontent.com/474290/56620179-e58dd980-65dc-11e9-836b-f1167746acbc.png">

**Comment by AmandaBirmingham** [comment]
@wasade Could you help me work out the reproduction path for this?  Looking at the screenshots on this issue and #479, I tried to follow the steps shown but wasn't able to get the same result (see attached gif). Alternately, if you have the full error message of which the top part is shown in the animated gif above, that might help me hunt this down ...

![reproduce_420](https://user-images.githubusercontent.com/10677935/56761954-7dadcf00-6753-11e9-8ad6-1625ddf956a3.gif)

**Comment by AmandaBirmingham** [comment]
Ping @wasade can you provide any more reproduction guidance?

**Comment by AmandaBirmingham** [comment]
@wasade  It appears to me that this issue is now the ONLY one for 0.1.0 that still has an outstanding question.  We need to nail this down if we are going to get it into the next release.  Can you estimate when you will have a window to provide more guidance on its reproduction?

**Comment by wasade** [comment]
I apologize, I thought I had responded. Away from my laptop for a short while, will look at recreating with additional info after.

**Comment by wasade** [comment]
To recreate:

1) Pools -> Prepare amplicon sequencing library
2) Add a shotgun pool
3) Sequencing runs -> Prepare sequencing run
4) Add the pooled shotgun pool
5) Download the sample sheet

![issue_420](https://user-images.githubusercontent.com/474290/57116679-84b47e80-6d0b-11e9-8f3b-e63cfbd33f96.gif)

**Comment by AmandaBirmingham** [comment]
@wasade  Thank you, that is extremely helpful!
