### ISSUE TITLE
Use initials instead of email addresses

### ISSUE THREAD

**Issue by charles-cowart** [jdereus/labman#421]
Wet-lab requests that initials (MB, JT, etc.) are used for display purposes in Labman, instead of using email addresses. Specific page(s) weren't given, but presumably this includes 'Sequence Run List' at the least.

With respect to the above page, it may also be prudent to change the name of the column from 'PI' to something else.

**Comment by charles-cowart** [comment]
Labcontrol relies on Qiita's user data for access control, however it does keep a list of Qiita users w/access to Labcontrol in the table: labman.labmanager_access. The best way of implementing this would be to add a second column in this table to store an email's associated initials, and then create them when the user is given Labcontrol access; this metadata field doesn't apply to most Qiita users, hence it shouldn't be a burden on Qiita to maintain.

There should also be a configuration page where the user can change it, if they find that the automatically generated version is unsuitable. The code that implements this functionality will append integers to distinguish to new users, if their initials coincide with a current and/or previous user.

**Comment by antgonza** [comment]
Should this be in Qiita? I mean the user can change their name in Qiita, then LabControl can check the name/initials; not sure worth expending effort doing in two places. Note that we could even use the same cookie secret if we wanted both systems to have the same cookies.

**Comment by charles-cowart** [comment]
If you think it’s no trouble.

**Comment by antgonza** [comment]
I _think_ it should be fine but let's discuss in the Qiita meeting.

**Comment by ackermag** [comment]
Greg and I signed off on using email addresses instead of initials in development meetings.  Email addresses are more helpful for trouble-shooting when time has passed and people are no longer in the wetlab and not remembered from initials.

**Comment by charles-cowart** [comment]
Closing per Gail's request.
