### ISSUE TITLE
Change "Preparation File" to "Mapping File"

### ISSUE THREAD

**Issue by charles-cowart** [jdereus/labman#422]
Wet-lab requests that 'Preparation File' be changed to 'Mapping File'. Specific page(s) weren't given, but presumably this includes 'Sequence Run List' at the least.

**Comment by wasade** [comment]
Please verify this with Gail

**Comment by charles-cowart** [comment]
Will do!

**Comment by wasade** [comment]
Thanks!

**Comment by antgonza** [comment]
Yes, let's verify with Gail cause a mapping file, traditionally has been a qiime mapping file, which is a combination of sample and prep information file ... which is what qiita generates. This is important to avoid confusion within and between users and developers.

**Comment by ackermag** [comment]
Do not agree to retain the designation "mapping file".  As @antgonza says a mapping file is usually Qiime mapping file.  We are outputting all the required info for a prep file in Qiita.

**Comment by charles-cowart** [comment]
Closing, as it appears there is good reason not to make the change.
