### ISSUE TITLE
Update Labcontrol unit tests.

### ISSUE THREAD

**Issue by charles-cowart** [jdereus/labman#424]
Unit tests in TestPlateConfiguration should be updated to account for new database column 'creation_timestamp'. Tests can also be updated to be more flexible.

**Comment by charles-cowart** [comment]
@wasade Just to clarify, I believe we're going to rollback the creation_timestamp change, correct? If so, we can close this issue out as moot, won't-fix.

**Comment by wasade** [comment]
:+1:
