### ISSUE TITLE
Verify AGP barcodes match between legacy mapping files and LC-generated.

### ISSUE THREAD

**Issue by charles-cowart** [jdereus/labman#426]
"[Wetlab] checked 3 barcodes in AGP between our own mapping files, and the ones that lab control generated and they seemed fine." Wetlab is requesting if there is a better way to ensure that all of them match. This can probably be done programmatically in an iPython Notebook.

**Comment by ackermag** [comment]
It can easily be done in Excel - I have shown Julia and MacKenzie how to check that all are correct and map to the original output.

**Comment by charles-cowart** [comment]
Closing at Gail's request.
