### ISSUE TITLE
Project_name column in prep sheet is empty in controls output

### ISSUE THREAD

**Issue by ackermag** [jdereus/labman#431]
Should reflect the project that the blanks/controls refer to.

**Comment by charles-cowart** [comment]
@ackermag I might need clarification on where this is occurring in the user interface.

**Comment by charles-cowart** [comment]
To clarify, this is the 16S workflow's prep-information-file download (controls output file - 1 file of 2).

**Comment by charles-cowart** [comment]
Confirmed Project_name column is empty in controls output. @ackermag says we can pull project_name 'Palmer_11479' from the sample_plate column ('Palmer_11479_Plate_1') for now, if need be (ignoring case where two projects are on the same plate.) Note samples file does have a populated Project name column ('Palmer GWAS, SG_B0014')

**Comment by charles-cowart** [comment]
The code strongly suggests that study.study_alias is blank for controls:

study.study_alias AS project_name

result['project_name'] isn't touched in any way, until the column name is changed to 'Project_name'. I thought this was worth making a note of. At least for the short term, we'll probably have to copy and modify the value in the 'sample_plate' column.

**Comment by AmandaBirmingham** [comment]
This issue and https://github.com/jdereus/labman/issues/483 are not the same, but they are *definitely* kissing cousins.  Please keep both in mind when attempting a fix.

**Comment by AmandaBirmingham** [comment]
See #483 for question

**Comment by AmandaBirmingham** [comment]
When solving this issue, we may want to determine if it intersects with/is affected by #387 "Add new `was_pooled` field to amplicon prep file for blanks" ... e.g., does it make sense to assign blanks/controls to a particular project if they weren't ever actually pooled (and thus sequenced)?  My understanding is that in the amplicon pipeline, usually only 2 blanks are pooled; see below.

https://github.com/jdereus/labman/blob/645c798e0094e9962973c2d111c4860b1e8e5b23/labcontrol/gui/handlers/process_handlers/pooling_process.py#L238-L243

**Comment by charles-cowart** [comment]
@AmandaBirmingham Is this a question for @ackermag? My thought was that every control would be part of a project, but you're saying that if the control/blank wasn't plated, you'd prefer for it to remain blank in the controls prep sheet?

**Comment by AmandaBirmingham** [comment]
@charles-cowart Given today's discussion, that will not be the case: ALL controls on a plate will get the study for that plate, and labcontrol will not create output for any case where a plate has >1 study on it (to avoid creating misleading output).  I will modify the issues to reflect our conclusions either tonight or tomorrow morning.
