### ISSUE TITLE
Change error message so error location(cell, row, column) is referenced

### ISSUE THREAD

**Issue by ackermag** [jdereus/labman#433]
Right now error message reads as "line nnn..." which doesn't apply to actual plate map line.
This would be nice to have
<img width="571" alt="Screen Shot 2019-04-05 at 7 21 40 AM" src="https://user-images.githubusercontent.com/2014592/55634580-a43fa200-5773-11e9-88f0-580331cf8325.png">

**Comment by wasade** [comment]
Please see the comment history on #434
