### ISSUE TITLE
Creating a plate map with sequential numbers generates an error

### ISSUE THREAD

**Issue by ackermag** [jdereus/labman#434]
Error attached and plate map attached.
<img width="571" alt="Screen Shot 2019-04-05 at 7 21 40 AM" src="https://user-images.githubusercontent.com/2014592/55634882-4069a900-5774-11e9-91b2-ffb2f56cbcfe.png">
<img width="848" alt="Screen Shot 2019-04-05 at 7 29 22 AM" src="https://user-images.githubusercontent.com/2014592/55635068-aa824e00-5774-11e9-85ac-cd2dc25683e6.png">

**Comment by ackermag** [comment]
We found a work-around for this by adding a letter to the sample number

**Comment by wasade** [comment]
@charles-cowart @AmandaBirmingham, the script noted here was authored by @qiyunzhu. This script is presently used *if LabControl* is not involved in the plating process. However, the correctness of the outputs from `LabControl` are based on a comparison to the results of this script.

@charles-cowart @AmandaBirmingham, have either of you seen this script? If the answer is no, @qiyunzhu, can you email the script to them?

I am closing this issue as the problem noted here is not technically part of LabControl.

**Comment by charles-cowart** [comment]
@wasade I have not seen this script. If Labcontrol output is supposed to match, this is an issue, right?
@ackermag Thanks! I'm a little confused however; you guys added a letter to the sample number, but I don't see sample numbers in the image above.

**Comment by ackermag** [comment]
@charles-cowart The second screen shot shows the plate map for these samples.  The letter (R) was added to the number in the individual cells.

**Comment by charles-cowart** [comment]
@ackermag Thanks! It's not clear to me whether the second image is Labcontrol, or this script @wasade mentioned; LC would be highlighting errors, for example.

**Comment by wasade** [comment]
@charles-cowart, this screenshot is not from LabControl, same with the screenshot in #433. The critical item here is: this is a process the lab actively performs which LabControl is to be compared against.
