### ISSUE TITLE
only able to work on one sheet at a time

### ISSUE THREAD

**Issue by jdereus** [jdereus/labman#44]
what if multiple people are working on a project, or if I want to prepare the plate maps for samples and have flexibility to easily move a bunch of samples from one plate to the other

**Comment by josenavas** [comment]
I think I don't understand this issue - can you specify?

**Comment by jdereus** [comment]
what if multiple people are working on a project, or if I want to prepare the plate maps for samples and have flexibility to easily move a bunch of samples from one plate to the other?

**Comment by josenavas** [comment]
Related to #26 - Fixing this will allow to do #26

**Comment by josenavas** [comment]
Rolling #26 into this issue since they're duplicated: when selecting multiple plates in the listing page, all of them should be seen here.

Semar is working on this.

**Comment by josenavas** [comment]
After talking with Lindsay it looks like this functionality is not required. I have to double-check with Greg as per Lindsay request (but he will not be available until later today).

**Comment by AmandaBirmingham** [comment]
I can't even figure out what this is asking for, and whatever it is it sounds like the wet lab didn't require it.
