### ISSUE TITLE
Change labman start command from start_webserver to start-webserver

### ISSUE THREAD

**Issue by AmandaBirmingham** [jdereus/labman#453]
This commit 
https://github.com/jdereus/labman/commit/661b5cada2faf5bc717da85aff5e9ba410a67425#diff-04c6e90faac2675aa89e2176d2eec7d8

changed the README.md to say labcontrol is started with the command `labman start-webserver`.  However, running that command with the current master gives

```
(labman) Amandas-MacBook-Pro-6:labman Birmingham$ labman start-webserver
Usage: labman [OPTIONS] COMMAND [ARGS]...

Error: No such command "start-webserver".
```

The actual command apparently remains `labman start_webserver` (which is what runs successfully): https://github.com/jdereus/labman/blob/0b05cd0da7a8acaecfc2092ed34d0dbe2229fb6b/scripts/labman#L23

I assume the goal is to make the code match the readme.

**Comment by antgonza** [comment]
I _think_ this is a click version "feature", my guess is that locally you have an older version of click, try: `pip install -U click` and try again ...

**Comment by AmandaBirmingham** [comment]
Hmm, should it matter if I update through `pip` or `conda`?  In my `labman` conda environment, I ran 

`conda update -n labman click`

which then updated the following packages:

`click: 6.7-py36_0 --> 7.0-py36_0`

However, when I run `labman start-webserver`  I still get the error

```
(labman) Amandas-MacBook-Pro-6:labman Birmingham$ labman start-webserver
Usage: labman [OPTIONS] COMMAND [ARGS]...
Try "labman --help" for help.

Error: No such command "start-webserver".
```

I also note that `.travis.yml` is using `start_webserver` (with the underscore):

https://github.com/jdereus/labman/blob/a3b8f5366bc1c045c135e19a8f556116addf34c9/.travis.yml#L80

**Comment by antgonza** [comment]
Thanks for the extra info. Now, I don't know what's going on. Click latests is 7.0, so that's correct. Weird ...

**Comment by charles-cowart** [comment]
I noticed this too a while back. IMHO, there's something to be said for having a more uniform command line interface across the software products. It removes surprise during deployment, and looks professional. What about 'labcontrol webserver start' ?

**Comment by charles-cowart** [comment]
Changed this from start_webserver to start-webserver during the last few rounds of labman -> labcontrol renaming. Closing.

**Comment by AmandaBirmingham** [comment]
Looks like somehow this didn't officially get closed, but I agree it should be.
