### ISSUE TITLE
Lab Control Plate samples workflow character restrictions impede sample matching to sample identifier.

### ISSUE THREAD

**Issue by RodolfoSalido** [jdereus/labman#456]
When plating iMSMS project (11326), which has column 'Tube_ID' as sample identifier, Lab Control GUI character restrictions make it impossible for one to match the 'Tube_ID' value because 'Tube_ID' is not character restricted. 

For more context, the iMSMS project provided plate maps with some samples with special characters. These were captured in the metadata column 'Tube_ID'.

<img width="1439" alt="Screen Shot 2019-04-16 at 11 10 47 AM" src="https://user-images.githubusercontent.com/13193891/56234597-780d0680-603a-11e9-8381-7517cb8d1ee8.png">

When trying to plate samples, the Lab Control GUI deletes the space in between  'Mag' and 'Bead' and fails to match the sample name in the 'Tube_ID' column of the metadata. 

<img width="1440" alt="Screen Shot 2019-04-16 at 11 11 05 AM" src="https://user-images.githubusercontent.com/13193891/56234770-d9cd7080-603a-11e9-8c53-982ba4894709.png">

**Comment by AmandaBirmingham** [comment]
The cause of this behavior is in `/labcontrol/gui/static/js/plateViewer.js`'s `this.applyValue` function:

https://github.com/jdereus/labman/blob/645c798e0094e9962973c2d111c4860b1e8e5b23/labcontrol/gui/static/js/plateViewer.js#L608

This line strips out all whitespace.  Note, however, that even if it didn't, the subsequent lines

https://github.com/jdereus/labman/blob/645c798e0094e9962973c2d111c4860b1e8e5b23/labcontrol/gui/static/js/plateViewer.js#L614-L615

... would still bollox the tube id in question.

I *think* we can get away with removing these validation replacements now that the input into the plate is no longer expected to be a qiita sample id, so it no longer needs to follow qiita sample id format rules.  @ElDeveloper , do you agree or no?

**Comment by ElDeveloper** [comment]
@AmandaBirmingham, from looking at the UI code that sounds right to me. However, I would advise that someone checked if any other component of the project expects this type of validation (for example the code that submits the request to add the data). And other than that, I would try to figure out why was this added i.e. if this was expected or if it is a common use-case when plating "certain types of samples".
