### ISSUE TITLE
Normalization workflow minor changes. (Volume units, default values)

### ISSUE THREAD

**Issue by RodolfoSalido** [jdereus/labman#457]
### Minor changes to metagenomics input normalization workflow.

- The default parameter for the 'Min Volume' field in the input normalization workflow for metagenomics should be 25 and not 2.5 in order to match our Jupyter notebook default parameters. 
<img width="1181" alt="Screen Shot 2019-04-16 at 12 10 59 PM" src="https://user-images.githubusercontent.com/13193891/56237761-9cb8ac80-6041-11e9-84f4-e5bde65742fb.png">
<img width="1035" alt="Screen Shot 2019-04-16 at 12 15 33 PM" src="https://user-images.githubusercontent.com/13193891/56237675-6d09a480-6041-11e9-9ad4-3cfc54259f52.png">

- All fields asking for volumes should display units in parentheses. (nL)

**Comment by antgonza** [comment]
@RodolfoSalido, Looking at the 2 screenshots, is it possible that resolution (2.5 in notebook) is not present in GUI and min_vol is fine (25 in both)?

**Comment by RodolfoSalido** [comment]
> @RodolfoSalido, Looking at the 2 screenshots, is it possible that resolution (2.5 in notebook) is not present in GUI and min_vol is fine (25 in both)?

I didn't do the best job with my screenshots, I apologize. The GUI does have resolution parameter too. Here's a screenshot of Lab Control's normalization workflow default parameters.
<img width="1226" alt="Screen Shot 2019-04-16 at 12 29 15 PM" src="https://user-images.githubusercontent.com/13193891/56238438-654aff80-6043-11e9-872a-f0ec62ba65a8.png">

**Comment by antgonza** [comment]
@RodolfoSalido, thank you for confirming.

**Comment by AmandaBirmingham** [comment]
@RodolfoSalido Below is a screenshot of changes I am proposing to address this issue.  Please compare this to the OLD settings (see second screenshot below) and let me know if I've gotten the fixes right! :)

**Proposed new:**
![Screen Shot 2019-04-25 at 3 50 37 PM](https://user-images.githubusercontent.com/10677935/56773179-f02da780-6771-11e9-98ee-b2d95cbe9dcc.png)


**Old:**
![Screen Shot 2019-04-25 at 3 38 58 PM](https://user-images.githubusercontent.com/10677935/56773089-96c57880-6771-11e9-903e-130421b015bf.png)

**Comment by AmandaBirmingham** [comment]
Ping @RodolfoSalido Could you approve/disapprove the above proposed changes?  Thanks!

**Comment by RodolfoSalido** [comment]
Sorry, I thought I had replied. This changes are what we wanted.

Thanks!

-Rodolfo
