### ISSUE TITLE
use arrow keys to navigate sheets

### ISSUE THREAD

**Issue by jdereus** [jdereus/labman#46]
not just trackpad and the enter key

**Comment by josenavas** [comment]
This is a bit tricky - I'm actively disabling the interaction with keys. When the user starts typing a new sample, a "dropdown" shows with the available samples. Using the up/down keys allows the user to choose the sample from that drop down, but if it is enabled in the spreadsheet, it will move the cell w/o choosing the sample. Does that make sense?

**Comment by josenavas** [comment]
This is enabled but not when you're editing the cell - Add a comment to specify that.

**Comment by josenavas** [comment]
This has been discussed with the wet lab and agreed that current functionality works.
