### ISSUE TITLE
Metagenomics Sample Sheet generation introduces spaces in 'Sample_project' column.

### ISSUE THREAD

**Issue by RodolfoSalido** [jdereus/labman#482]
Lab Control introduces space characters in 'Sample_Project' column because it appends the Qiita study owner. Spaces are not permitted within this column for the downstream workflows (this field specifies the directory where the demultiplexed data will be deposited). 

<img width="1415" alt="Screen Shot 2019-04-24 at 10 56 57 AM" src="https://user-images.githubusercontent.com/13193891/56682166-dad85080-667f-11e9-9e4f-f0439af78140.png">

**Comment by AmandaBirmingham** [comment]
@RodolfoSalido  Aha!  How would you like us to doctor the qiita study owner name in order to make it usable for downstream purposes?

**Comment by RodolfoSalido** [comment]
I believe that replacing spaces with underscores will be appropriate. The formatted name will be the name for the directory where the demultiplexed data will be deposited.

**Comment by charles-cowart** [comment]
Thanks @RodolfoSalido! Does this sound all right with you, @ghsmu414?

**Comment by AmandaBirmingham** [comment]
Before we have everyone sign off, let's take the opportunity to decide on other potential problem characters.  Whitespace becomes an underscore--check.  What about any other non alpha-numeric characters that might appear in a name?  Hyphens should be fine in a folder name, but what about, say, apostrophes (e.g., "O'Brien")?  @antgonza do you know if there are any limits on what characters can appear in a study owner name in Qiita?  Trying to figure out if LabControl needs to defensively scrub or if that will already have been done ...

**Comment by charles-cowart** [comment]
@AmandaBirmingham Qiita's filters on names will allow all printable ASCII characters, if I'm not mistaken. The filters are primarily to filter out Unicode, etc. characters.

**Comment by antgonza** [comment]
@charles-cowart and @AmandaBirmingham , that's correct but it will allow ' and also icons; cause I guess they are valid? See the list of newly created names in my local install:
![Screen Shot 2019-04-25 at 10 51 59 AM](https://user-images.githubusercontent.com/2014559/56753663-4be33b00-6748-11e9-9af2-ca31d3f8068a.png)

**Comment by AmandaBirmingham** [comment]
@antgonza Whoa! :)  Ok, so I guess the requirements for fixing this issue are:
1) Replace whitespace with underscore
2) Replace any characters (other than whitespace) *that aren't valid in a folder name* with **X**--where X is whatever filler character is approved by the stakeholders.  Could be an empty string if they just want us to elide these characters.

@RodolfoSalido @ghsmu414 @jdereus I think you're the relevant stakeholders.  Please add in anyone I missed and talk amongst yourselves to decide what you want us to use for **X** !

**Comment by charles-cowart** [comment]
@antgonza icons? That's interesting, as the filter is defined as 'anything not within the printable ASCII range'. Not sure if anyone is going to be using icons any time soon...

**Comment by antgonza** [comment]
After seeing that this was possible, I was thinking in: "Antonio Gonzalez 👑 "

**Comment by jdereus** [comment]
Project and sample names in the sample sheet cannot contain illegal characters not allowed by some file systems.   The characters not allowed are the space character and the following

? ( ) [ ] / \ = + < > : ; “ ‘ , * ^ | & .

**Comment by AmandaBirmingham** [comment]
Ping @ghsmu414 @RodolfoSalido @jdereus I haven't heard an opinion on what you want us to replace any character that ISN'T whitespace with (e.g., if if PI name is "O'Brien", do we replace ' with - to get O-Brien? Or do we just remove that character altogether to get OBrien? etc).  Please let us know what you want!

**Comment by RodolfoSalido** [comment]
If the hyphen doesn't introduce issues, then I think it is a good solution as a substitution for restricted characters. Underscore will replace whitespace characters while a hyphen will replace all other restricted characters. 

-Rodolfo

**Comment by jdereus** [comment]
Seems fine to me for hyphen.
