### ISSUE TITLE
Describe versioning scheme 

### ISSUE THREAD

**Issue by wasade** [jdereus/labman#487]
For milestone 4, we began associating versions as at the completion of the milestone, a new version of labcontrol will be cut.

The repo presently, and loosely, uses the QIIME2 syntax, e.g. 2019.4. For this milestone, it is currently labeled using a more traditional semantic versioning, e.g., 0.1.0. Both versioning schemes are in use with projects in the lab. The 0.1.0 format as major version bump indicates things such as full launch, minor version bumps being functionality, major bug fixes, etc, and microversion bumps being no change to the overall user experience but project improvements such as the test framework. 

However, there is certainly merit for versioning based off of date as it is immediately clear when the release was. 

If there is a strong preference for one over the other, then let's proceed with the preference. The label if this milestone is not set in stone and will be updated if necessary for use in the associated release.

**Comment by antgonza** [comment]
IMOO date makes sense when dealing with fast changing tools, like LC; once the tool/features are more stable we can adopt the number format. However, I don't have a strong preference ...

**Comment by charles-cowart** [comment]
IMHO, date is more intuitive, at least for right now. No strong preference.

**Comment by AmandaBirmingham** [comment]
@wasade Can you clarify what the deliverable for this issue is?  Currently scoping our progress :)

**Comment by wasade** [comment]
A paragraph of text in the readme describing the version structure, minimal locations where the version is specified (ideally a single location), and how that version number changes. It is not necessary to, for example, use `versioneer` as is used in QIIME2. However, that would be a bonus.
