### ISSUE TITLE
Provide way to see status of samples per Qiita study

### ISSUE THREAD

**Issue by adswafford** [jdereus/labman#50]
Diagram, list, table, etc. 

Could at minimum be a summary, e.g:
1) Select Qiita study
2) Display-
Plated: 500/500 samples 
Extracted: 384/500 samples 
Amplified: 384/500 samples 
Quantified: 384/500 samples 
Pooled: 192/500 samples 
Sequenced: 88/500 samples

Very open to other ideas, so long as it's possible to see where things are in the system somehow.

**Comment by josenavas** [comment]
@qiyunzhu and @mortonjt are working on this.
