### ISSUE TITLE
PoolingProcess._format_picklist() produces incorrect output if populating >15 destination wells (on a 384-well plate) 

### ISSUE THREAD

**Issue by AmandaBirmingham** [jdereus/labman#505]
For the test data for PoolingProcess(3) in the test db, the volume in every well of the 384-well input plate is 1 nL except for wells 0 23 and 24 and P 23 and 24, which are empty.  In this, case, when entering a max_vol_per_well of 1 nL, one would expect each input well to go into a separate output well (except for the 4 noted above), so there should be 380 output wells (A1-P20).  See attached expected output:

[expected_poollist.txt](https://github.com/jdereus/labman/files/3160400/expected_poollist.txt)

However, the code in fact produces output that works as expected up to A15 and then sends output to B16-B23, then B0[sic]-B7, then C8-C23, and so on in unexpected ways until X20 (spoiler: not a real 384-well-plate well :) See attached buggy output:

[buggy_poollist.txt](https://github.com/jdereus/labman/files/3160408/buggy_poollist.txt)

**Comment by AmandaBirmingham** [comment]
I have hunted down the cause of this behavior, which is due to the interaction of three separate bugs in the below section of the method:

https://github.com/jdereus/labman/blob/46241e448edd4fc615aeea914e8dd80bf88aad79/labcontrol/db/process.py#L2534-L2549

Issue 1: 
https://github.com/jdereus/labman/blob/46241e448edd4fc615aeea914e8dd80bf88aad79/labcontrol/db/process.py#L2548

This line is intended to find what integer to add to the ascii code for the letter "A" to find the row letter of the destination well (e.g., ascii for A is 097, so if this line returns the integer 1, we add 1 to 097 and get 098, which is the ascii code for B, etc)--let's call this the row increment.  `d` is the number of the current destination well.  We need to increase the row increment every time `d` indicates we have filled another row--that is, every time `d` goes up by the number of COLUMNS contained in a row.  Unfortunately, the number of COLUMNS on the destination plate is `dest_plate_shape[1]`, and this code is erroneously using the number of ROWS on the plate (`dest_plate_shape[0]`).  That is why the buggy output mistakenly "turns over" to a new row on the 16th destination well (because the number of rows on a 384-well plate is 16).

Issue 2:

Even after correcting issue 1 above, the code doesn't work QUITE right: it turns over to a new row on the 24th destination well, whereas in fact it shouldn't turn over to a new row until the *25th* (e.g., the 24th well should be A24, not B1).  This is most easily solved by treating `d` as the destination well *index* (0-based), starting at `d = 0` rather than `d = 1`.  With this change, the 24th destination well has `d = 23` and thus has a row increment of `np.floor(23/24)`, or 0, so it remains part of row A.

Issue 3.  

https://github.com/jdereus/labman/blob/46241e448edd4fc615aeea914e8dd80bf88aad79/labcontrol/db/process.py#L2549

This line is intended to find the column number of the destination well--as in., the "1" in "A1".  However,  this modulo calculation comes out to zero (not a valid column number) every time `d` is an exact multiple of the number of columns on the plate (e.g., 24, 48, etc).  The fix for this, in conjunction with the fix above to issue 3 that starts `d` at zero, is to simply add 1 to the modulo results.

Thus, the *corrected* section of the method code reads as below, with the modified values shown surrounded by double asterisks:

```
        d = **0**
        for i in range(rows):
            for j in range(cols):
                well_name = "%s%d" % (chr(ord('A') + i), j + 1)
                # Machine will round, so just give it enough info to do the
                # correct rounding.
                val = "%.2f" % pool_vols[i][j]
                # test to see if we will exceed total vol per well
                if running_tot + pool_vols[i][j] > max_vol_per_well:
                    d += 1
                    running_tot = pool_vols[i][j]
                else:
                    running_tot += pool_vols[i][j]
                dest = "%s%d" % (chr(ord('A') +
                                 int(np.floor(d / dest_plate_shape[**1**]))),
                                 (d % dest_plate_shape[1]) **+1**)
```

**Comment by AmandaBirmingham** [comment]
**Please note:** it looks like the LabControl method being discussed here may come verbatim from https://github.com/tanaes/metagenomics_pooling_notebook/blob/cf93b57d70f3a36f1321bd2b7a78275e358f7178/metapool/metapool.py#L451-L496 , and thus the fixes described above may need to be propagated to that code if it is still in use.

**Comment by AmandaBirmingham** [comment]
Also note that even with the corrections above, this code will output garbage in either of the two edge cases below:

1. you don't have enough wells to pool all the input volumes, given the max vol per well
2. an individual input well has > the max vol per well

**Comment by charles-cowart** [comment]
@AmandaBirmingham I think I can close this one as well?

**Comment by AmandaBirmingham** [comment]
Not yet (but hopefully soon!) Just put in the PR for this one: https://github.com/jdereus/labman/pull/515
