### ISSUE TITLE
Implement tester.py equivalent for gui

### ISSUE THREAD

**Issue by AmandaBirmingham** [jdereus/labman#522]
populate w code that loads index.html (the test runner page) into headless chrome and captures results

**Comment by charles-cowart** [comment]
@josenavas, @tanaes Do you guys remember why we have tester.py? It appears to be something to load test classes and run them according to supplied parameters. However, all the tests are subclassed from LabControlTestCase, which in turn is subclassed from unit test's own TestCase class. Hence, I'm kind of wondering why we have a second entry point to run unit-tests? It seems like we could run every test through nosetests?

**Comment by charles-cowart** [comment]
Related to #523. See comments.

**Comment by charles-cowart** [comment]
Resolved by #527
