### ISSUE TITLE
Shotgun pipeline: interface list

### ISSUE THREAD

**Issue by tanaes** [jdereus/labman#60]
This is a list top-level issue specifying interfaces that still need to be made to link to code to enable a complete shotgun prep run. 

1. [x] **gDNA plate compression**
  - inputs: 1-4 extracted gDNA plates
  - outputs: compressed gDNA plate
  - purpose: move plates from 96-well to 384-well format for use with Echo robot
2. [x] **gDNA plate normalization**
  - inputs: miniPico DNA quantification; compressed gDNA plate
  - outputs: normalized gDNA plate
  - purpose: creates the 384-well normalized gDNA plate for library prep
3. [x] **Assign index/barcodes**
  - inputs: normalized gDNA plate
  - outputs: Echo pick list file for adding barcodes to library prep plate
  - purpose: assign index sequences and create instructions file for adding them on Echo robot
4. [x] **Pool shotgun libraries**
  - inputs: normalized gDNA plate (with assigned indices); miniPico library quantification
  - outputs: Echo pick list file for pooling libraries; library pool 
  - purpose: pool libraries for sequencing
5. [x] **Make sample sheet**
  - inputs: one or more library pools
  - outputs: Illumina-compatible Sample Sheet file
  - purpose: makes file for running sequencer and demultiplexing

**Comment by josenavas** [comment]
All items in the list.
