### ISSUE TITLE
shotgun pipeline: add plate compression interface

### ISSUE THREAD

**Issue by tanaes** [jdereus/labman#61]
We extract DNA in 96-well plates, but the robots we use for shotgun library prep require 384-well plates. Thus, we need to combine or "compress" 96-well plates into 384-well format, and to keep a record of this. 

This interface should:
1. Accept 1-4 extracted gDNA plates in 96-well format
2. Create a new compressed gDNA plate

**Comment by josenavas** [comment]
Fixed in #66
