### ISSUE TITLE
shotgun pipeline: gDNA normalization interface

### ISSUE THREAD

**Issue by tanaes** [jdereus/labman#62]
For best results, we need to put approximately the same amount of gDNA into the library prep protocol. To do this, we first measure the concentration of gDNA in our compressed gDNA plate, and then create an instructions file to give to an Echo robot to combine samples with water to end up with a certain quantity of DNA in a set volume for input into the library prep chemistry. 

This interface should:
1. Take a compressed gDNA plate
2. accept an uploaded DNA quantification file as produced by our plate reader
3. take some values from the user:
  - total ending volume (per well)
  - min and max gDNA volume to add
  - Echo robot dispense resolution
  - desired DNA quantity
4. produce an Echo pick-list formatted file and a normalized gDNA plate

**Comment by josenavas** [comment]
Being solved in #55
