### ISSUE TITLE
shotgun pipeline: library prep process + assign barcodes interface

### ISSUE THREAD

**Issue by tanaes** [jdereus/labman#63]
Once we have normalized gDNA plates, we can continue on with shotgun library prep. This process will record information about the kit lots and robots used for the library prep by the wetlab. We will also need to assign unique barcode sequence primers to each sample so that we can pool and demultiplex later. Physically, this happens on the Echo robot, which adds unique i5 and i7 barcoded primers separately to each sample. We have 384 unique i5 and i7 barcodes, so in practice, we will only ever be using one of each per 384-well library prep plate—the database will record the combinations that have been used, so that we never repeat *particular* combinations until *all* 147456 unique combos have been used. 

This interface will need user input for:
- the Kapa HyperPlus kit lot # used (and maybe some other information)
- the iTru adapter stub lot # and/or aliquot used
- the barcode set used
- the barcode plate replicate used

It will then output:
- an echo pick list file for adding the unique barcodes to the sample

**Comment by josenavas** [comment]
Fixed in #68
