### ISSUE TITLE
shotgun pipeline: library pooling interface

### ISSUE THREAD

**Issue by tanaes** [jdereus/labman#64]
Once libraries have been made, we pool them together for multiplexed sequencing. 

To do this, we add quantitation information to the plates. Currently, this is done with the same miniPico protocol we use for gDNA quantification. The DNA concentration then goes through a function that estimates library concentration. From the estimated library concentrations, pooling values are calculated and an Echo pick list is generated. 

Currently, the thinking is that the quantification information upload / addition will happen with the normal or a separate DNA concentration upload page or interface. 

This interface should take as input from the user: 
- the pooling algorithm to use (for example equal volume or 'minvol') 
- the input parameters for the pooling algorithm

It should produce: 
- a visualization of the pooling estimates
- once accepted, an Echo pick list for pooling

**Comment by josenavas** [comment]
Being solved in #71

**Comment by josenavas** [comment]
Solved in #71
