### ISSUE TITLE
shotgun pipeline: sequencing process interface

### ISSUE THREAD

**Issue by tanaes** [jdereus/labman#65]
Once we have pooled and barcoded samples, we can send them off to the sequencer. 

To do this, we need to select: 
- The sequencer type (e.g. HiSeq4000, HiSeq2500 rapid run, MiSeq)
- The lanes used (defined by the sequencer type)
- the pools assigned per lane
- some other information values

It will then create an Illumina compatible sample sheet to provide to the sequencer/ sequencing facility

**Comment by josenavas** [comment]
Being solved in #70

**Comment by josenavas** [comment]
Fixed
