### ISSUE TITLE
figure generation and return/display

### ISSUE THREAD

**Issue by tanaes** [jdereus/labman#69]
There are a lot of steps that would benefit from / absolutely need some sort of visual feedback to illustrate the success of particular steps. 

For example, see the plate concentration visualization images from the current shotgun pipeline [Jupyter notebooks](https://github.com/tanaes/metagenomics_pooling_notebook/blob/master/metagenomics_pipeline_MiniPiconorm.ipynb):

<img width="626" alt="screenshot" src="https://user-images.githubusercontent.com/8292608/35077467-69036be0-fbb2-11e7-83d8-a0d2de760358.png">

These plate visualizations should be displayed when uploading anything that quantifies DNA per well of a plate, providing a visual check to indicate that things worked—for example, on the Plate Quantification interface, or the Library Pooling interface. 

The code for this particular figure generation is [already written](https://github.com/tanaes/metagenomics_pooling_notebook/blob/f3f9e6add8472df9663adb9bb995da238c550a5e/metapool/metapool.py#L489). We just need a way to deploy and integrate into the HTML / Javascript interface.

**Comment by ElDeveloper** [comment]
As per @josenavas' and @tanaes's suggestion, this issue ties in very well with #112. @nreeve17 and I are working on this to create an interactive heatmap that displays the quantities and sample identifiers.
