### ISSUE TITLE
Add extra information to prep information

### ISSUE THREAD

**Issue by josenavas** [jdereus/labman#94]
Amplicon and Shotgun preps:

- gDNA extraction process data
    - epmotion robot
    - epmotion tool
    - kingfisher robot
    - extraction kit

Amplicon preps:
- library prep 16s process data
    - epmotion
    - tm300 tool
    - tm50 tool
    - master mix
    - water
- primer_composition
    - Find the plate that contains this primer composition (through the composition -> well -> plate) chain and add the plate name (that is the primer working plate)
- primer_set_composition
    - barcode_seq (for demultiplexing)

Shotgun preps:
- normalization process
    - water lot
- library prep shotgun process
    - kappa hyper plus kit
    - stub lot

As fas as I know those are the columns to include - I think the rest of the columns for shotgun are already included in the current prep generation. @ackermag, @tanaes can you think of any other column not included? It may be easier to spot once a complete prep information file is generated, but wanted to check if there is anything that pops on your head.

**Comment by ackermag** [comment]
I have been adding other columns for shotgun Kapperhyperplus prep templates.  Attached here is an example of one such from the AG submission.  It is a different process because there are additional standard fields.  We may need to adjust some of these lab generated fields as well
[prep_RKL0005_AGP5-6_16_168_scrubbed.txt](https://github.com/jdereus/labman/files/1654248/prep_RKL0005_AGP5-6_16_168_scrubbed.txt)

**Comment by josenavas** [comment]
Thanks for the information! @antgonza let me know if you need support finding any of those fields in the DB.

**Comment by antgonza** [comment]
@josenavas, yes; an extended list of table->attribute will be great, thanks!

**Comment by josenavas** [comment]
@antgonza The issue description contains the list of table -> attributes
I've omitted the "_" in the name of the tables/attributes. For those that are "id" on their table, you just need to do a join with the necessary equipment/reagentcomposition table to get the external id.

For example:
```SQL
SELECT rc.external_lot_id, eq_ep.external_id, eq_tool.external_id, eq_kf.external_id
FROM qiita.gDNA_extraction_process_data gdna
    JOIN qiita.reagent_composition rc ON gdna.extraction_kit_id = rc.reagent_composition_id
    JOIN qiita.equipment eq_ep ON gdna.epmotion_robot_id = eq_ep.equipment_id
    JOIN qiita.equipment eq_tool ON gdna.epmotion_tool_id = eq_tool.equipment_id
    JOIN qiita.equipment eq_kf ON gdna.kingfisher_robot_id = eq_kf.equipment_id
```

and similarly for the other tables

**Comment by antgonza** [comment]
Yes, but is that list comprehensive with the example that @ackermag sent?

**Comment by josenavas** [comment]
Missing columns:
- run_prefix:
    - Shotgun: it should be the bcl2fastq sample name that the sample sheet is generating
    - Amplicon: it should be the run_name
- sample_plate:
    - Shotgun & Amplicon: The plate in which the sample_composition_id is present (follow sample_composition -> composition -> well -> plate)
- sample_well
    - Shotgun & Amplicon: The well in which the sample_composition_id is present in the plate (follow sample_composition -> composition -> well  to get the row/column values and check the code [here](https://github.com/jdereus/labman/blob/master/labman/db/container.py#L270) to format the well.
- library_construction_protocol:
    - @ackermag can you provide the valid values that we should put on this column?
- sequencing_meth:
    - Is this value: "Sequencing by synthesis"
- platform:
    - Is this value: "Illumina"
- center_project_name
    - sequencing_process.experiment_name

Note that the sequencing meth and platform are right now hardcoded - a more complex structure of the equipment table would be needed to store this values in the DB and make it dynamic. However, I don't think that's blocking.

**Comment by antgonza** [comment]
Got it, thanks!

**Comment by josenavas** [comment]
This has been fixed.
