### ISSUE TITLE
Sample sheets download as html files

### ISSUE THREAD

**Issue by tanaes** [jdereus/labman#96]
When I click on the 'download sample sheet' link it downloads as a .csv.html file.

**Comment by josenavas** [comment]
@tanaes I can't reproduce this issue - when I download the file, it gets downloaded as a .csv file. Is that some kind of setting on your browser?

**Comment by tanaes** [comment]
Looks like this is happening in Safari but not chrome. Traced the problem to:

```python
        self.set_header('Content-Description', 'text/csv')
        self.set_header('Expires', '0')
        self.set_header('Cache-Control', 'no-cache')
        self.set_header('Content-Disposition',
                        'attachment; filename=%s' % filename)
        self.write(text)
```

Changing `Content-Description` to `Content-Type` resolves the problem. Submitting a PR.

**Comment by jdereus** [comment]
can i look at a representative sample of what you expect the sample sheet to look like?  have you gotten input from wetlab members on structure?

**Comment by tanaes** [comment]
Here ya go. Had to modify extension to upload here but it's usually .csv

[YYYY_MM_DD_FinRisk_33-36_samplesheet.txt](https://github.com/jdereus/labman/files/1657131/YYYY_MM_DD_FinRisk_33-36_samplesheet.txt)
