### ISSUE TITLE
Library pooling isn't working

### ISSUE THREAD

**Issue by tanaes** [jdereus/labman#98]
On current master (e11c183), the library pooling doesn't work for me. 

1. if I select `Amplicon library plates`, it does not let me add the example test plate---green button appears, but clicking does nothing. <img width="578" alt="screenshot" src="https://user-images.githubusercontent.com/8292608/35258564-31636080-ffb5-11e7-89dc-10848b8fd415.png">
2. if I select `Shotgun library plates`, it allows me to add the example plate and select a pooling function, but then throws an error. <img width="580" alt="screenshot" src="https://user-images.githubusercontent.com/8292608/35258576-48418f66-ffb5-11e7-9fae-5239757991df.png">

**Comment by josenavas** [comment]
@tanaes That is weird - that page is working without a problem for me and that function is defined here: https://github.com/jdereus/labman/blob/master/labman/gui/static/js/labman.js#L38

Is your browser caching the JS libraries? Make sure to disable caching when developing HTML. On Google Chrome, caching automatically gets disabled when opening the Developer console, not sure about other browsers.

**Comment by tanaes** [comment]
Yup, that did it. 

Now, getting missing parameter errors with shotgun pooling:

<img width="541" alt="screenshot" src="https://user-images.githubusercontent.com/8292608/35259538-52bf2268-ffbb-11e7-9ea6-1b7fb08a1481.png">

**Comment by tanaes** [comment]
that is with min-vol  (top), floor-vol (mid), and eq-vol (bottom).

**Comment by josenavas** [comment]
Thanks @tanaes - working on it
